/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Lockally.SDK.Model;
using Lockally.SDK.Client;
using System.Reflection;

namespace Lockally.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing CalendarPolicies
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CalendarPoliciesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CalendarPolicies
        //private CalendarPolicies instance;

        public CalendarPoliciesTests()
        {
            // TODO uncomment below to create an instance of CalendarPolicies
            //instance = new CalendarPolicies();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CalendarPolicies
        /// </summary>
        [Fact]
        public void CalendarPoliciesInstanceTest()
        {
            // TODO uncomment below to test "IsType" CalendarPolicies
            //Assert.IsType<CalendarPolicies>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'MaxMeetingDurationMins'
        /// </summary>
        [Fact]
        public void MaxMeetingDurationMinsTest()
        {
            // TODO unit test for the property 'MaxMeetingDurationMins'
        }

        /// <summary>
        /// Test the property 'WorkingHoursStart'
        /// </summary>
        [Fact]
        public void WorkingHoursStartTest()
        {
            // TODO unit test for the property 'WorkingHoursStart'
        }

        /// <summary>
        /// Test the property 'WorkingHoursEnd'
        /// </summary>
        [Fact]
        public void WorkingHoursEndTest()
        {
            // TODO unit test for the property 'WorkingHoursEnd'
        }

        /// <summary>
        /// Test the property 'BookingWindowDays'
        /// </summary>
        [Fact]
        public void BookingWindowDaysTest()
        {
            // TODO unit test for the property 'BookingWindowDays'
        }

        /// <summary>
        /// Test the property 'RecurringMeetingLimit'
        /// </summary>
        [Fact]
        public void RecurringMeetingLimitTest()
        {
            // TODO unit test for the property 'RecurringMeetingLimit'
        }

        /// <summary>
        /// Test the property 'ResourceApprovalMode'
        /// </summary>
        [Fact]
        public void ResourceApprovalModeTest()
        {
            // TODO unit test for the property 'ResourceApprovalMode'
        }

        /// <summary>
        /// Test the property 'ExternalInvitesAllowed'
        /// </summary>
        [Fact]
        public void ExternalInvitesAllowedTest()
        {
            // TODO unit test for the property 'ExternalInvitesAllowed'
        }

        /// <summary>
        /// Test the property 'ExternalSharingAllowed'
        /// </summary>
        [Fact]
        public void ExternalSharingAllowedTest()
        {
            // TODO unit test for the property 'ExternalSharingAllowed'
        }

        /// <summary>
        /// Test the property 'PublicLinksEnabled'
        /// </summary>
        [Fact]
        public void PublicLinksEnabledTest()
        {
            // TODO unit test for the property 'PublicLinksEnabled'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
