/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Lockally.SDK.Model;
using Lockally.SDK.Client;
using System.Reflection;

namespace Lockally.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing GALSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GALSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GALSettings
        //private GALSettings instance;

        public GALSettingsTests()
        {
            // TODO uncomment below to create an instance of GALSettings
            //instance = new GALSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GALSettings
        /// </summary>
        [Fact]
        public void GALSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" GALSettings
            //Assert.IsType<GALSettings>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'GalEnabled'
        /// </summary>
        [Fact]
        public void GalEnabledTest()
        {
            // TODO unit test for the property 'GalEnabled'
        }

        /// <summary>
        /// Test the property 'HideFromDirectory'
        /// </summary>
        [Fact]
        public void HideFromDirectoryTest()
        {
            // TODO unit test for the property 'HideFromDirectory'
        }

        /// <summary>
        /// Test the property 'DepartmentGrouping'
        /// </summary>
        [Fact]
        public void DepartmentGroupingTest()
        {
            // TODO unit test for the property 'DepartmentGrouping'
        }

        /// <summary>
        /// Test the property 'SearchVisibility'
        /// </summary>
        [Fact]
        public void SearchVisibilityTest()
        {
            // TODO unit test for the property 'SearchVisibility'
        }

        /// <summary>
        /// Test the property 'IncludeExternalContacts'
        /// </summary>
        [Fact]
        public void IncludeExternalContactsTest()
        {
            // TODO unit test for the property 'IncludeExternalContacts'
        }

        /// <summary>
        /// Test the property 'LastIndexRebuiltAt'
        /// </summary>
        [Fact]
        public void LastIndexRebuiltAtTest()
        {
            // TODO unit test for the property 'LastIndexRebuiltAt'
        }

        /// <summary>
        /// Test the property 'LastSyncedAt'
        /// </summary>
        [Fact]
        public void LastSyncedAtTest()
        {
            // TODO unit test for the property 'LastSyncedAt'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
