/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Lockally.SDK.Model;
using Lockally.SDK.Client;
using System.Reflection;

namespace Lockally.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing GetCalendarSecurity200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetCalendarSecurity200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetCalendarSecurity200Response
        //private GetCalendarSecurity200Response instance;

        public GetCalendarSecurity200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetCalendarSecurity200Response
            //instance = new GetCalendarSecurity200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetCalendarSecurity200Response
        /// </summary>
        [Fact]
        public void GetCalendarSecurity200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetCalendarSecurity200Response
            //Assert.IsType<GetCalendarSecurity200Response>(instance);
        }

        /// <summary>
        /// Test the property 'TotalCalendars'
        /// </summary>
        [Fact]
        public void TotalCalendarsTest()
        {
            // TODO unit test for the property 'TotalCalendars'
        }

        /// <summary>
        /// Test the property 'PublicCalendars'
        /// </summary>
        [Fact]
        public void PublicCalendarsTest()
        {
            // TODO unit test for the property 'PublicCalendars'
        }

        /// <summary>
        /// Test the property 'PrivateCalendars'
        /// </summary>
        [Fact]
        public void PrivateCalendarsTest()
        {
            // TODO unit test for the property 'PrivateCalendars'
        }

        /// <summary>
        /// Test the property 'TotalMembers'
        /// </summary>
        [Fact]
        public void TotalMembersTest()
        {
            // TODO unit test for the property 'TotalMembers'
        }

        /// <summary>
        /// Test the property 'DelegatedAccess'
        /// </summary>
        [Fact]
        public void DelegatedAccessTest()
        {
            // TODO unit test for the property 'DelegatedAccess'
        }

        /// <summary>
        /// Test the property 'PublicCalendarList'
        /// </summary>
        [Fact]
        public void PublicCalendarListTest()
        {
            // TODO unit test for the property 'PublicCalendarList'
        }

        /// <summary>
        /// Test the property 'Alerts'
        /// </summary>
        [Fact]
        public void AlertsTest()
        {
            // TODO unit test for the property 'Alerts'
        }

        /// <summary>
        /// Test the property 'ExternalSharing'
        /// </summary>
        [Fact]
        public void ExternalSharingTest()
        {
            // TODO unit test for the property 'ExternalSharing'
        }
    }
}
