/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Lockally.SDK.Model;
using Lockally.SDK.Client;
using System.Reflection;

namespace Lockally.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing MigrationProgressMailboxesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MigrationProgressMailboxesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MigrationProgressMailboxesInner
        //private MigrationProgressMailboxesInner instance;

        public MigrationProgressMailboxesInnerTests()
        {
            // TODO uncomment below to create an instance of MigrationProgressMailboxesInner
            //instance = new MigrationProgressMailboxesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MigrationProgressMailboxesInner
        /// </summary>
        [Fact]
        public void MigrationProgressMailboxesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" MigrationProgressMailboxesInner
            //Assert.IsType<MigrationProgressMailboxesInner>(instance);
        }

        /// <summary>
        /// Test the property 'SourceEmail'
        /// </summary>
        [Fact]
        public void SourceEmailTest()
        {
            // TODO unit test for the property 'SourceEmail'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'SyncedMessageCount'
        /// </summary>
        [Fact]
        public void SyncedMessageCountTest()
        {
            // TODO unit test for the property 'SyncedMessageCount'
        }

        /// <summary>
        /// Test the property 'FailedMessageCount'
        /// </summary>
        [Fact]
        public void FailedMessageCountTest()
        {
            // TODO unit test for the property 'FailedMessageCount'
        }

        /// <summary>
        /// Test the property 'PercentComplete'
        /// </summary>
        [Fact]
        public void PercentCompleteTest()
        {
            // TODO unit test for the property 'PercentComplete'
        }

        /// <summary>
        /// Test the property 'DestEmail'
        /// </summary>
        [Fact]
        public void DestEmailTest()
        {
            // TODO unit test for the property 'DestEmail'
        }

        /// <summary>
        /// Test the property 'SourceMessageCount'
        /// </summary>
        [Fact]
        public void SourceMessageCountTest()
        {
            // TODO unit test for the property 'SourceMessageCount'
        }
    }
}
