/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Lockally.SDK.Model;
using Lockally.SDK.Client;
using System.Reflection;

namespace Lockally.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing MigrationSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MigrationSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MigrationSettings
        //private MigrationSettings instance;

        public MigrationSettingsTests()
        {
            // TODO uncomment below to create an instance of MigrationSettings
            //instance = new MigrationSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MigrationSettings
        /// </summary>
        [Fact]
        public void MigrationSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" MigrationSettings
            //Assert.IsType<MigrationSettings>(instance);
        }

        /// <summary>
        /// Test the property 'MaxConcurrentMailboxes'
        /// </summary>
        [Fact]
        public void MaxConcurrentMailboxesTest()
        {
            // TODO unit test for the property 'MaxConcurrentMailboxes'
        }

        /// <summary>
        /// Test the property 'MaxConcurrentMessages'
        /// </summary>
        [Fact]
        public void MaxConcurrentMessagesTest()
        {
            // TODO unit test for the property 'MaxConcurrentMessages'
        }

        /// <summary>
        /// Test the property 'SourceRateLimit'
        /// </summary>
        [Fact]
        public void SourceRateLimitTest()
        {
            // TODO unit test for the property 'SourceRateLimit'
        }

        /// <summary>
        /// Test the property 'BatchSize'
        /// </summary>
        [Fact]
        public void BatchSizeTest()
        {
            // TODO unit test for the property 'BatchSize'
        }

        /// <summary>
        /// Test the property 'SkipFolders'
        /// </summary>
        [Fact]
        public void SkipFoldersTest()
        {
            // TODO unit test for the property 'SkipFolders'
        }
    }
}
