// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// APIKey
    /// </summary>
    public partial class APIKey : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="APIKey" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="tenantId">tenantId</param>
        /// <param name="prefix">8-char public prefix; safe to store and display.</param>
        /// <param name="scopes">scopes</param>
        /// <param name="label">label</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="lastUsedAt">lastUsedAt</param>
        /// <param name="revokedAt">revokedAt</param>
        [JsonConstructor]
        public APIKey(Guid id, Guid tenantId, string prefix, List<string> scopes, string label, DateTime createdAt, Option<DateTime?> lastUsedAt = default, Option<DateTime?> revokedAt = default)
        {
            Id = id;
            TenantId = tenantId;
            Prefix = prefix;
            Scopes = scopes;
            Label = label;
            CreatedAt = createdAt;
            LastUsedAtOption = lastUsedAt;
            RevokedAtOption = revokedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenant_id")]
        public Guid TenantId { get; set; }

        /// <summary>
        /// 8-char public prefix; safe to store and display.
        /// </summary>
        /// <value>8-char public prefix; safe to store and display.</value>
        /* <example>fbl73bhj</example> */
        [JsonPropertyName("prefix")]
        public string Prefix { get; set; }

        /// <summary>
        /// Gets or Sets Scopes
        /// </summary>
        [JsonPropertyName("scopes")]
        public List<string> Scopes { get; set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        /* <example>ci-pipeline</example> */
        [JsonPropertyName("label")]
        public string Label { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of LastUsedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> LastUsedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastUsedAt
        /// </summary>
        [JsonPropertyName("last_used_at")]
        public DateTime? LastUsedAt { get { return this.LastUsedAtOption.Value; } set { this.LastUsedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of RevokedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> RevokedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets RevokedAt
        /// </summary>
        [JsonPropertyName("revoked_at")]
        public DateTime? RevokedAt { get { return this.RevokedAtOption.Value; } set { this.RevokedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class APIKey {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  Prefix: ").Append(Prefix).Append("\n");
            sb.Append("  Scopes: ").Append(Scopes).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  LastUsedAt: ").Append(LastUsedAt).Append("\n");
            sb.Append("  RevokedAt: ").Append(RevokedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="APIKey" />
    /// </summary>
    public class APIKeyJsonConverter : JsonConverter<APIKey>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize LastUsedAt
        /// </summary>
        public static string LastUsedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize RevokedAt
        /// </summary>
        public static string RevokedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="APIKey" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override APIKey Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> tenantId = default;
            Option<string?> prefix = default;
            Option<List<string>?> scopes = default;
            Option<string?> label = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> lastUsedAt = default;
            Option<DateTime?> revokedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "tenant_id":
                            tenantId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "prefix":
                            prefix = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "scopes":
                            scopes = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "label":
                            label = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "last_used_at":
                            lastUsedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "revoked_at":
                            revokedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class APIKey.", nameof(id));

            if (!tenantId.IsSet)
                throw new ArgumentException("Property is required for class APIKey.", nameof(tenantId));

            if (!prefix.IsSet)
                throw new ArgumentException("Property is required for class APIKey.", nameof(prefix));

            if (!scopes.IsSet)
                throw new ArgumentException("Property is required for class APIKey.", nameof(scopes));

            if (!label.IsSet)
                throw new ArgumentException("Property is required for class APIKey.", nameof(label));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class APIKey.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class APIKey.");

            if (tenantId.IsSet && tenantId.Value == null)
                throw new ArgumentNullException(nameof(tenantId), "Property is not nullable for class APIKey.");

            if (prefix.IsSet && prefix.Value == null)
                throw new ArgumentNullException(nameof(prefix), "Property is not nullable for class APIKey.");

            if (scopes.IsSet && scopes.Value == null)
                throw new ArgumentNullException(nameof(scopes), "Property is not nullable for class APIKey.");

            if (label.IsSet && label.Value == null)
                throw new ArgumentNullException(nameof(label), "Property is not nullable for class APIKey.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class APIKey.");

            if (lastUsedAt.IsSet && lastUsedAt.Value == null)
                throw new ArgumentNullException(nameof(lastUsedAt), "Property is not nullable for class APIKey.");

            if (revokedAt.IsSet && revokedAt.Value == null)
                throw new ArgumentNullException(nameof(revokedAt), "Property is not nullable for class APIKey.");

            return new APIKey(id.Value!.Value!, tenantId.Value!.Value!, prefix.Value!, scopes.Value!, label.Value!, createdAt.Value!.Value!, lastUsedAt, revokedAt);
        }

        /// <summary>
        /// Serializes a <see cref="APIKey" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="aPIKey"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, APIKey aPIKey, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, aPIKey, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="APIKey" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="aPIKey"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, APIKey aPIKey, JsonSerializerOptions jsonSerializerOptions)
        {
            if (aPIKey.Prefix == null)
                throw new ArgumentNullException(nameof(aPIKey.Prefix), "Property is required for class APIKey.");

            if (aPIKey.Scopes == null)
                throw new ArgumentNullException(nameof(aPIKey.Scopes), "Property is required for class APIKey.");

            if (aPIKey.Label == null)
                throw new ArgumentNullException(nameof(aPIKey.Label), "Property is required for class APIKey.");

            writer.WriteString("id", aPIKey.Id);

            writer.WriteString("tenant_id", aPIKey.TenantId);

            writer.WriteString("prefix", aPIKey.Prefix);

            writer.WritePropertyName("scopes");
            JsonSerializer.Serialize(writer, aPIKey.Scopes, jsonSerializerOptions);
            writer.WriteString("label", aPIKey.Label);

            writer.WriteString("created_at", aPIKey.CreatedAt.ToString(CreatedAtFormat));

            if (aPIKey.LastUsedAtOption.IsSet)
                writer.WriteString("last_used_at", aPIKey.LastUsedAtOption.Value!.Value.ToString(LastUsedAtFormat));

            if (aPIKey.RevokedAtOption.IsSet)
                writer.WriteString("revoked_at", aPIKey.RevokedAtOption.Value!.Value.ToString(RevokedAtFormat));
        }
    }
}
