// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// Contact
    /// </summary>
    public partial class Contact : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Contact" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="tenantId">tenantId</param>
        /// <param name="name">name</param>
        /// <param name="email">email</param>
        /// <param name="contactType">contactType</param>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="phone">phone</param>
        /// <param name="company">company</param>
        /// <param name="notes">notes</param>
        /// <param name="source">source</param>
        /// <param name="department">department</param>
        /// <param name="role">role</param>
        [JsonConstructor]
        public Contact(Guid id, Guid tenantId, string name, string email, ContactTypeEnum contactType, string status, DateTime createdAt, DateTime updatedAt, Option<string?> phone = default, Option<string?> company = default, Option<string?> notes = default, Option<string?> source = default, Option<string?> department = default, Option<string?> role = default)
        {
            Id = id;
            TenantId = tenantId;
            Name = name;
            Email = email;
            ContactType = contactType;
            Status = status;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            PhoneOption = phone;
            CompanyOption = company;
            NotesOption = notes;
            SourceOption = source;
            DepartmentOption = department;
            RoleOption = role;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines ContactType
        /// </summary>
        public enum ContactTypeEnum
        {
            /// <summary>
            /// Enum Internal for value: internal
            /// </summary>
            Internal = 1,

            /// <summary>
            /// Enum External for value: external
            /// </summary>
            External = 2
        }

        /// <summary>
        /// Returns a <see cref="ContactTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ContactTypeEnum ContactTypeEnumFromString(string value)
        {
            if (value.Equals("internal"))
                return ContactTypeEnum.Internal;

            if (value.Equals("external"))
                return ContactTypeEnum.External;

            throw new NotImplementedException($"Could not convert value to type ContactTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ContactTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ContactTypeEnum? ContactTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("internal"))
                return ContactTypeEnum.Internal;

            if (value.Equals("external"))
                return ContactTypeEnum.External;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ContactTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ContactTypeEnumToJsonValue(ContactTypeEnum value)
        {
            if (value == ContactTypeEnum.Internal)
                return "internal";

            if (value == ContactTypeEnum.External)
                return "external";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets ContactType
        /// </summary>
        [JsonPropertyName("contact_type")]
        public ContactTypeEnum ContactType { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenant_id")]
        public Guid TenantId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Used to track the state of Phone
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PhoneOption { get; private set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [JsonPropertyName("phone")]
        public string? Phone { get { return this.PhoneOption.Value; } set { this.PhoneOption = new(value); } }

        /// <summary>
        /// Used to track the state of Company
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CompanyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Company
        /// </summary>
        [JsonPropertyName("company")]
        public string? Company { get { return this.CompanyOption.Value; } set { this.CompanyOption = new(value); } }

        /// <summary>
        /// Used to track the state of Notes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NotesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [JsonPropertyName("notes")]
        public string? Notes { get { return this.NotesOption.Value; } set { this.NotesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Source
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [JsonPropertyName("source")]
        public string? Source { get { return this.SourceOption.Value; } set { this.SourceOption = new(value); } }

        /// <summary>
        /// Used to track the state of Department
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DepartmentOption { get; private set; }

        /// <summary>
        /// Gets or Sets Department
        /// </summary>
        [JsonPropertyName("department")]
        public string? Department { get { return this.DepartmentOption.Value; } set { this.DepartmentOption = new(value); } }

        /// <summary>
        /// Used to track the state of Role
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RoleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [JsonPropertyName("role")]
        public string? Role { get { return this.RoleOption.Value; } set { this.RoleOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Contact {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  ContactType: ").Append(ContactType).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  Company: ").Append(Company).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Department: ").Append(Department).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Contact" />
    /// </summary>
    public class ContactJsonConverter : JsonConverter<Contact>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Contact" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Contact Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> tenantId = default;
            Option<string?> name = default;
            Option<string?> email = default;
            Option<Contact.ContactTypeEnum?> contactType = default;
            Option<string?> status = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> updatedAt = default;
            Option<string?> phone = default;
            Option<string?> company = default;
            Option<string?> notes = default;
            Option<string?> source = default;
            Option<string?> department = default;
            Option<string?> role = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "tenant_id":
                            tenantId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "contact_type":
                            string? contactTypeRawValue = utf8JsonReader.GetString();
                            if (contactTypeRawValue != null)
                                contactType = new Option<Contact.ContactTypeEnum?>(Contact.ContactTypeEnumFromStringOrDefault(contactTypeRawValue));
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updated_at":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "phone":
                            phone = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "company":
                            company = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "notes":
                            notes = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "source":
                            source = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "department":
                            department = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "role":
                            role = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Contact.", nameof(id));

            if (!tenantId.IsSet)
                throw new ArgumentException("Property is required for class Contact.", nameof(tenantId));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class Contact.", nameof(name));

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class Contact.", nameof(email));

            if (!contactType.IsSet)
                throw new ArgumentException("Property is required for class Contact.", nameof(contactType));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class Contact.", nameof(status));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class Contact.", nameof(createdAt));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class Contact.", nameof(updatedAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Contact.");

            if (tenantId.IsSet && tenantId.Value == null)
                throw new ArgumentNullException(nameof(tenantId), "Property is not nullable for class Contact.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class Contact.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class Contact.");

            if (contactType.IsSet && contactType.Value == null)
                throw new ArgumentNullException(nameof(contactType), "Property is not nullable for class Contact.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class Contact.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Contact.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class Contact.");

            if (phone.IsSet && phone.Value == null)
                throw new ArgumentNullException(nameof(phone), "Property is not nullable for class Contact.");

            if (company.IsSet && company.Value == null)
                throw new ArgumentNullException(nameof(company), "Property is not nullable for class Contact.");

            if (notes.IsSet && notes.Value == null)
                throw new ArgumentNullException(nameof(notes), "Property is not nullable for class Contact.");

            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source), "Property is not nullable for class Contact.");

            if (department.IsSet && department.Value == null)
                throw new ArgumentNullException(nameof(department), "Property is not nullable for class Contact.");

            if (role.IsSet && role.Value == null)
                throw new ArgumentNullException(nameof(role), "Property is not nullable for class Contact.");

            return new Contact(id.Value!.Value!, tenantId.Value!.Value!, name.Value!, email.Value!, contactType.Value!.Value!, status.Value!, createdAt.Value!.Value!, updatedAt.Value!.Value!, phone, company, notes, source, department, role);
        }

        /// <summary>
        /// Serializes a <see cref="Contact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="contact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Contact contact, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, contact, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Contact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="contact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Contact contact, JsonSerializerOptions jsonSerializerOptions)
        {
            if (contact.Name == null)
                throw new ArgumentNullException(nameof(contact.Name), "Property is required for class Contact.");

            if (contact.Email == null)
                throw new ArgumentNullException(nameof(contact.Email), "Property is required for class Contact.");

            if (contact.Status == null)
                throw new ArgumentNullException(nameof(contact.Status), "Property is required for class Contact.");

            if (contact.PhoneOption.IsSet && contact.Phone == null)
                throw new ArgumentNullException(nameof(contact.Phone), "Property is required for class Contact.");

            if (contact.CompanyOption.IsSet && contact.Company == null)
                throw new ArgumentNullException(nameof(contact.Company), "Property is required for class Contact.");

            if (contact.NotesOption.IsSet && contact.Notes == null)
                throw new ArgumentNullException(nameof(contact.Notes), "Property is required for class Contact.");

            if (contact.SourceOption.IsSet && contact.Source == null)
                throw new ArgumentNullException(nameof(contact.Source), "Property is required for class Contact.");

            if (contact.DepartmentOption.IsSet && contact.Department == null)
                throw new ArgumentNullException(nameof(contact.Department), "Property is required for class Contact.");

            if (contact.RoleOption.IsSet && contact.Role == null)
                throw new ArgumentNullException(nameof(contact.Role), "Property is required for class Contact.");

            writer.WriteString("id", contact.Id);

            writer.WriteString("tenant_id", contact.TenantId);

            writer.WriteString("name", contact.Name);

            writer.WriteString("email", contact.Email);

            var contactTypeRawValue = Contact.ContactTypeEnumToJsonValue(contact.ContactType);
            writer.WriteString("contact_type", contactTypeRawValue);
            writer.WriteString("status", contact.Status);

            writer.WriteString("created_at", contact.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("updated_at", contact.UpdatedAt.ToString(UpdatedAtFormat));

            if (contact.PhoneOption.IsSet)
                writer.WriteString("phone", contact.Phone);

            if (contact.CompanyOption.IsSet)
                writer.WriteString("company", contact.Company);

            if (contact.NotesOption.IsSet)
                writer.WriteString("notes", contact.Notes);

            if (contact.SourceOption.IsSet)
                writer.WriteString("source", contact.Source);

            if (contact.DepartmentOption.IsSet)
                writer.WriteString("department", contact.Department);

            if (contact.RoleOption.IsSet)
                writer.WriteString("role", contact.Role);
        }
    }
}
