// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// CreateBillingCheckoutRequest
    /// </summary>
    public partial class CreateBillingCheckoutRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateBillingCheckoutRequest" /> class.
        /// </summary>
        /// <param name="plan">plan</param>
        [JsonConstructor]
        public CreateBillingCheckoutRequest(PlanEnum plan)
        {
            Plan = plan;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Plan
        /// </summary>
        public enum PlanEnum
        {
            /// <summary>
            /// Enum Free for value: free
            /// </summary>
            Free = 1,

            /// <summary>
            /// Enum Founder for value: founder
            /// </summary>
            Founder = 2,

            /// <summary>
            /// Enum Starter for value: starter
            /// </summary>
            Starter = 3,

            /// <summary>
            /// Enum Pro for value: pro
            /// </summary>
            Pro = 4,

            /// <summary>
            /// Enum Scale for value: scale
            /// </summary>
            Scale = 5
        }

        /// <summary>
        /// Returns a <see cref="PlanEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static PlanEnum PlanEnumFromString(string value)
        {
            if (value.Equals("free"))
                return PlanEnum.Free;

            if (value.Equals("founder"))
                return PlanEnum.Founder;

            if (value.Equals("starter"))
                return PlanEnum.Starter;

            if (value.Equals("pro"))
                return PlanEnum.Pro;

            if (value.Equals("scale"))
                return PlanEnum.Scale;

            throw new NotImplementedException($"Could not convert value to type PlanEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="PlanEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static PlanEnum? PlanEnumFromStringOrDefault(string value)
        {
            if (value.Equals("free"))
                return PlanEnum.Free;

            if (value.Equals("founder"))
                return PlanEnum.Founder;

            if (value.Equals("starter"))
                return PlanEnum.Starter;

            if (value.Equals("pro"))
                return PlanEnum.Pro;

            if (value.Equals("scale"))
                return PlanEnum.Scale;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="PlanEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string PlanEnumToJsonValue(PlanEnum value)
        {
            if (value == PlanEnum.Free)
                return "free";

            if (value == PlanEnum.Founder)
                return "founder";

            if (value == PlanEnum.Starter)
                return "starter";

            if (value == PlanEnum.Pro)
                return "pro";

            if (value == PlanEnum.Scale)
                return "scale";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Plan
        /// </summary>
        [JsonPropertyName("plan")]
        public PlanEnum Plan { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateBillingCheckoutRequest {\n");
            sb.Append("  Plan: ").Append(Plan).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateBillingCheckoutRequest" />
    /// </summary>
    public class CreateBillingCheckoutRequestJsonConverter : JsonConverter<CreateBillingCheckoutRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateBillingCheckoutRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateBillingCheckoutRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<CreateBillingCheckoutRequest.PlanEnum?> plan = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "plan":
                            string? planRawValue = utf8JsonReader.GetString();
                            if (planRawValue != null)
                                plan = new Option<CreateBillingCheckoutRequest.PlanEnum?>(CreateBillingCheckoutRequest.PlanEnumFromStringOrDefault(planRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!plan.IsSet)
                throw new ArgumentException("Property is required for class CreateBillingCheckoutRequest.", nameof(plan));

            if (plan.IsSet && plan.Value == null)
                throw new ArgumentNullException(nameof(plan), "Property is not nullable for class CreateBillingCheckoutRequest.");

            return new CreateBillingCheckoutRequest(plan.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CreateBillingCheckoutRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createBillingCheckoutRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateBillingCheckoutRequest createBillingCheckoutRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createBillingCheckoutRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateBillingCheckoutRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createBillingCheckoutRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateBillingCheckoutRequest createBillingCheckoutRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            var planRawValue = CreateBillingCheckoutRequest.PlanEnumToJsonValue(createBillingCheckoutRequest.Plan);
            writer.WriteString("plan", planRawValue);
        }
    }
}
