// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// GetCalendarSecurity200ResponsePublicCalendarListInner
    /// </summary>
    public partial class GetCalendarSecurity200ResponsePublicCalendarListInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetCalendarSecurity200ResponsePublicCalendarListInner" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="ownerEmail">ownerEmail</param>
        /// <param name="memberCount">memberCount</param>
        /// <param name="hasFeed">hasFeed</param>
        [JsonConstructor]
        public GetCalendarSecurity200ResponsePublicCalendarListInner(Option<Guid?> id = default, Option<string?> name = default, Option<string?> ownerEmail = default, Option<int?> memberCount = default, Option<bool?> hasFeed = default)
        {
            IdOption = id;
            NameOption = name;
            OwnerEmailOption = ownerEmail;
            MemberCountOption = memberCount;
            HasFeedOption = hasFeed;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of OwnerEmail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OwnerEmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets OwnerEmail
        /// </summary>
        [JsonPropertyName("owner_email")]
        public string? OwnerEmail { get { return this.OwnerEmailOption.Value; } set { this.OwnerEmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of MemberCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MemberCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets MemberCount
        /// </summary>
        [JsonPropertyName("member_count")]
        public int? MemberCount { get { return this.MemberCountOption.Value; } set { this.MemberCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of HasFeed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> HasFeedOption { get; private set; }

        /// <summary>
        /// Gets or Sets HasFeed
        /// </summary>
        [JsonPropertyName("has_feed")]
        public bool? HasFeed { get { return this.HasFeedOption.Value; } set { this.HasFeedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetCalendarSecurity200ResponsePublicCalendarListInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OwnerEmail: ").Append(OwnerEmail).Append("\n");
            sb.Append("  MemberCount: ").Append(MemberCount).Append("\n");
            sb.Append("  HasFeed: ").Append(HasFeed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetCalendarSecurity200ResponsePublicCalendarListInner" />
    /// </summary>
    public class GetCalendarSecurity200ResponsePublicCalendarListInnerJsonConverter : JsonConverter<GetCalendarSecurity200ResponsePublicCalendarListInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetCalendarSecurity200ResponsePublicCalendarListInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetCalendarSecurity200ResponsePublicCalendarListInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> name = default;
            Option<string?> ownerEmail = default;
            Option<int?> memberCount = default;
            Option<bool?> hasFeed = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "owner_email":
                            ownerEmail = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "member_count":
                            memberCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "has_feed":
                            hasFeed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class GetCalendarSecurity200ResponsePublicCalendarListInner.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class GetCalendarSecurity200ResponsePublicCalendarListInner.");

            if (ownerEmail.IsSet && ownerEmail.Value == null)
                throw new ArgumentNullException(nameof(ownerEmail), "Property is not nullable for class GetCalendarSecurity200ResponsePublicCalendarListInner.");

            if (memberCount.IsSet && memberCount.Value == null)
                throw new ArgumentNullException(nameof(memberCount), "Property is not nullable for class GetCalendarSecurity200ResponsePublicCalendarListInner.");

            if (hasFeed.IsSet && hasFeed.Value == null)
                throw new ArgumentNullException(nameof(hasFeed), "Property is not nullable for class GetCalendarSecurity200ResponsePublicCalendarListInner.");

            return new GetCalendarSecurity200ResponsePublicCalendarListInner(id, name, ownerEmail, memberCount, hasFeed);
        }

        /// <summary>
        /// Serializes a <see cref="GetCalendarSecurity200ResponsePublicCalendarListInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getCalendarSecurity200ResponsePublicCalendarListInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetCalendarSecurity200ResponsePublicCalendarListInner getCalendarSecurity200ResponsePublicCalendarListInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getCalendarSecurity200ResponsePublicCalendarListInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetCalendarSecurity200ResponsePublicCalendarListInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getCalendarSecurity200ResponsePublicCalendarListInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetCalendarSecurity200ResponsePublicCalendarListInner getCalendarSecurity200ResponsePublicCalendarListInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getCalendarSecurity200ResponsePublicCalendarListInner.NameOption.IsSet && getCalendarSecurity200ResponsePublicCalendarListInner.Name == null)
                throw new ArgumentNullException(nameof(getCalendarSecurity200ResponsePublicCalendarListInner.Name), "Property is required for class GetCalendarSecurity200ResponsePublicCalendarListInner.");

            if (getCalendarSecurity200ResponsePublicCalendarListInner.OwnerEmailOption.IsSet && getCalendarSecurity200ResponsePublicCalendarListInner.OwnerEmail == null)
                throw new ArgumentNullException(nameof(getCalendarSecurity200ResponsePublicCalendarListInner.OwnerEmail), "Property is required for class GetCalendarSecurity200ResponsePublicCalendarListInner.");

            if (getCalendarSecurity200ResponsePublicCalendarListInner.IdOption.IsSet)
                writer.WriteString("id", getCalendarSecurity200ResponsePublicCalendarListInner.IdOption.Value!.Value);

            if (getCalendarSecurity200ResponsePublicCalendarListInner.NameOption.IsSet)
                writer.WriteString("name", getCalendarSecurity200ResponsePublicCalendarListInner.Name);

            if (getCalendarSecurity200ResponsePublicCalendarListInner.OwnerEmailOption.IsSet)
                writer.WriteString("owner_email", getCalendarSecurity200ResponsePublicCalendarListInner.OwnerEmail);

            if (getCalendarSecurity200ResponsePublicCalendarListInner.MemberCountOption.IsSet)
                writer.WriteNumber("member_count", getCalendarSecurity200ResponsePublicCalendarListInner.MemberCountOption.Value!.Value);

            if (getCalendarSecurity200ResponsePublicCalendarListInner.HasFeedOption.IsSet)
                writer.WriteBoolean("has_feed", getCalendarSecurity200ResponsePublicCalendarListInner.HasFeedOption.Value!.Value);
        }
    }
}
