// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// GetIntegrationsSummary200Response
    /// </summary>
    public partial class GetIntegrationsSummary200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetIntegrationsSummary200Response" /> class.
        /// </summary>
        /// <param name="apiRequestsToday">apiRequestsToday</param>
        /// <param name="activeApiKeys">activeApiKeys</param>
        /// <param name="apiKeys">apiKeys</param>
        /// <param name="webhookFailures">webhookFailures</param>
        /// <param name="webhooksTotal">webhooksTotal</param>
        /// <param name="webhooks">webhooks</param>
        /// <param name="generatedAt">generatedAt</param>
        [JsonConstructor]
        public GetIntegrationsSummary200Response(Option<int?> apiRequestsToday = default, Option<int?> activeApiKeys = default, Option<List<GetIntegrationsSummary200ResponseApiKeysInner>?> apiKeys = default, Option<int?> webhookFailures = default, Option<int?> webhooksTotal = default, Option<List<GetIntegrationsSummary200ResponseWebhooksInner>?> webhooks = default, Option<DateTime?> generatedAt = default)
        {
            ApiRequestsTodayOption = apiRequestsToday;
            ActiveApiKeysOption = activeApiKeys;
            ApiKeysOption = apiKeys;
            WebhookFailuresOption = webhookFailures;
            WebhooksTotalOption = webhooksTotal;
            WebhooksOption = webhooks;
            GeneratedAtOption = generatedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ApiRequestsToday
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ApiRequestsTodayOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApiRequestsToday
        /// </summary>
        [JsonPropertyName("api_requests_today")]
        public int? ApiRequestsToday { get { return this.ApiRequestsTodayOption.Value; } set { this.ApiRequestsTodayOption = new(value); } }

        /// <summary>
        /// Used to track the state of ActiveApiKeys
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ActiveApiKeysOption { get; private set; }

        /// <summary>
        /// Gets or Sets ActiveApiKeys
        /// </summary>
        [JsonPropertyName("active_api_keys")]
        public int? ActiveApiKeys { get { return this.ActiveApiKeysOption.Value; } set { this.ActiveApiKeysOption = new(value); } }

        /// <summary>
        /// Used to track the state of ApiKeys
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<GetIntegrationsSummary200ResponseApiKeysInner>?> ApiKeysOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApiKeys
        /// </summary>
        [JsonPropertyName("api_keys")]
        public List<GetIntegrationsSummary200ResponseApiKeysInner>? ApiKeys { get { return this.ApiKeysOption.Value; } set { this.ApiKeysOption = new(value); } }

        /// <summary>
        /// Used to track the state of WebhookFailures
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> WebhookFailuresOption { get; private set; }

        /// <summary>
        /// Gets or Sets WebhookFailures
        /// </summary>
        [JsonPropertyName("webhook_failures")]
        public int? WebhookFailures { get { return this.WebhookFailuresOption.Value; } set { this.WebhookFailuresOption = new(value); } }

        /// <summary>
        /// Used to track the state of WebhooksTotal
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> WebhooksTotalOption { get; private set; }

        /// <summary>
        /// Gets or Sets WebhooksTotal
        /// </summary>
        [JsonPropertyName("webhooks_total")]
        public int? WebhooksTotal { get { return this.WebhooksTotalOption.Value; } set { this.WebhooksTotalOption = new(value); } }

        /// <summary>
        /// Used to track the state of Webhooks
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<GetIntegrationsSummary200ResponseWebhooksInner>?> WebhooksOption { get; private set; }

        /// <summary>
        /// Gets or Sets Webhooks
        /// </summary>
        [JsonPropertyName("webhooks")]
        public List<GetIntegrationsSummary200ResponseWebhooksInner>? Webhooks { get { return this.WebhooksOption.Value; } set { this.WebhooksOption = new(value); } }

        /// <summary>
        /// Used to track the state of GeneratedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> GeneratedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets GeneratedAt
        /// </summary>
        [JsonPropertyName("generated_at")]
        public DateTime? GeneratedAt { get { return this.GeneratedAtOption.Value; } set { this.GeneratedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetIntegrationsSummary200Response {\n");
            sb.Append("  ApiRequestsToday: ").Append(ApiRequestsToday).Append("\n");
            sb.Append("  ActiveApiKeys: ").Append(ActiveApiKeys).Append("\n");
            sb.Append("  ApiKeys: ").Append(ApiKeys).Append("\n");
            sb.Append("  WebhookFailures: ").Append(WebhookFailures).Append("\n");
            sb.Append("  WebhooksTotal: ").Append(WebhooksTotal).Append("\n");
            sb.Append("  Webhooks: ").Append(Webhooks).Append("\n");
            sb.Append("  GeneratedAt: ").Append(GeneratedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetIntegrationsSummary200Response" />
    /// </summary>
    public class GetIntegrationsSummary200ResponseJsonConverter : JsonConverter<GetIntegrationsSummary200Response>
    {
        /// <summary>
        /// The format to use to serialize GeneratedAt
        /// </summary>
        public static string GeneratedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="GetIntegrationsSummary200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetIntegrationsSummary200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> apiRequestsToday = default;
            Option<int?> activeApiKeys = default;
            Option<List<GetIntegrationsSummary200ResponseApiKeysInner>?> apiKeys = default;
            Option<int?> webhookFailures = default;
            Option<int?> webhooksTotal = default;
            Option<List<GetIntegrationsSummary200ResponseWebhooksInner>?> webhooks = default;
            Option<DateTime?> generatedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "api_requests_today":
                            apiRequestsToday = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "active_api_keys":
                            activeApiKeys = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "api_keys":
                            apiKeys = new Option<List<GetIntegrationsSummary200ResponseApiKeysInner>?>(JsonSerializer.Deserialize<List<GetIntegrationsSummary200ResponseApiKeysInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "webhook_failures":
                            webhookFailures = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "webhooks_total":
                            webhooksTotal = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "webhooks":
                            webhooks = new Option<List<GetIntegrationsSummary200ResponseWebhooksInner>?>(JsonSerializer.Deserialize<List<GetIntegrationsSummary200ResponseWebhooksInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "generated_at":
                            generatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (apiRequestsToday.IsSet && apiRequestsToday.Value == null)
                throw new ArgumentNullException(nameof(apiRequestsToday), "Property is not nullable for class GetIntegrationsSummary200Response.");

            if (activeApiKeys.IsSet && activeApiKeys.Value == null)
                throw new ArgumentNullException(nameof(activeApiKeys), "Property is not nullable for class GetIntegrationsSummary200Response.");

            if (apiKeys.IsSet && apiKeys.Value == null)
                throw new ArgumentNullException(nameof(apiKeys), "Property is not nullable for class GetIntegrationsSummary200Response.");

            if (webhookFailures.IsSet && webhookFailures.Value == null)
                throw new ArgumentNullException(nameof(webhookFailures), "Property is not nullable for class GetIntegrationsSummary200Response.");

            if (webhooksTotal.IsSet && webhooksTotal.Value == null)
                throw new ArgumentNullException(nameof(webhooksTotal), "Property is not nullable for class GetIntegrationsSummary200Response.");

            if (webhooks.IsSet && webhooks.Value == null)
                throw new ArgumentNullException(nameof(webhooks), "Property is not nullable for class GetIntegrationsSummary200Response.");

            if (generatedAt.IsSet && generatedAt.Value == null)
                throw new ArgumentNullException(nameof(generatedAt), "Property is not nullable for class GetIntegrationsSummary200Response.");

            return new GetIntegrationsSummary200Response(apiRequestsToday, activeApiKeys, apiKeys, webhookFailures, webhooksTotal, webhooks, generatedAt);
        }

        /// <summary>
        /// Serializes a <see cref="GetIntegrationsSummary200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getIntegrationsSummary200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetIntegrationsSummary200Response getIntegrationsSummary200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getIntegrationsSummary200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetIntegrationsSummary200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getIntegrationsSummary200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetIntegrationsSummary200Response getIntegrationsSummary200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getIntegrationsSummary200Response.ApiKeysOption.IsSet && getIntegrationsSummary200Response.ApiKeys == null)
                throw new ArgumentNullException(nameof(getIntegrationsSummary200Response.ApiKeys), "Property is required for class GetIntegrationsSummary200Response.");

            if (getIntegrationsSummary200Response.WebhooksOption.IsSet && getIntegrationsSummary200Response.Webhooks == null)
                throw new ArgumentNullException(nameof(getIntegrationsSummary200Response.Webhooks), "Property is required for class GetIntegrationsSummary200Response.");

            if (getIntegrationsSummary200Response.ApiRequestsTodayOption.IsSet)
                writer.WriteNumber("api_requests_today", getIntegrationsSummary200Response.ApiRequestsTodayOption.Value!.Value);

            if (getIntegrationsSummary200Response.ActiveApiKeysOption.IsSet)
                writer.WriteNumber("active_api_keys", getIntegrationsSummary200Response.ActiveApiKeysOption.Value!.Value);

            if (getIntegrationsSummary200Response.ApiKeysOption.IsSet)
            {
                writer.WritePropertyName("api_keys");
                JsonSerializer.Serialize(writer, getIntegrationsSummary200Response.ApiKeys, jsonSerializerOptions);
            }
            if (getIntegrationsSummary200Response.WebhookFailuresOption.IsSet)
                writer.WriteNumber("webhook_failures", getIntegrationsSummary200Response.WebhookFailuresOption.Value!.Value);

            if (getIntegrationsSummary200Response.WebhooksTotalOption.IsSet)
                writer.WriteNumber("webhooks_total", getIntegrationsSummary200Response.WebhooksTotalOption.Value!.Value);

            if (getIntegrationsSummary200Response.WebhooksOption.IsSet)
            {
                writer.WritePropertyName("webhooks");
                JsonSerializer.Serialize(writer, getIntegrationsSummary200Response.Webhooks, jsonSerializerOptions);
            }
            if (getIntegrationsSummary200Response.GeneratedAtOption.IsSet)
                writer.WriteString("generated_at", getIntegrationsSummary200Response.GeneratedAtOption.Value!.Value.ToString(GeneratedAtFormat));
        }
    }
}
