// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// GetStorage200ResponseTopMailboxesInner
    /// </summary>
    public partial class GetStorage200ResponseTopMailboxesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStorage200ResponseTopMailboxesInner" /> class.
        /// </summary>
        /// <param name="email">email</param>
        /// <param name="usageBytes">usageBytes</param>
        [JsonConstructor]
        public GetStorage200ResponseTopMailboxesInner(Option<string?> email = default, Option<long?> usageBytes = default)
        {
            EmailOption = email;
            UsageBytesOption = usageBytes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Email
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string? Email { get { return this.EmailOption.Value; } set { this.EmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of UsageBytes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> UsageBytesOption { get; private set; }

        /// <summary>
        /// Gets or Sets UsageBytes
        /// </summary>
        [JsonPropertyName("usage_bytes")]
        public long? UsageBytes { get { return this.UsageBytesOption.Value; } set { this.UsageBytesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetStorage200ResponseTopMailboxesInner {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  UsageBytes: ").Append(UsageBytes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetStorage200ResponseTopMailboxesInner" />
    /// </summary>
    public class GetStorage200ResponseTopMailboxesInnerJsonConverter : JsonConverter<GetStorage200ResponseTopMailboxesInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetStorage200ResponseTopMailboxesInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetStorage200ResponseTopMailboxesInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> email = default;
            Option<long?> usageBytes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "usage_bytes":
                            usageBytes = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class GetStorage200ResponseTopMailboxesInner.");

            if (usageBytes.IsSet && usageBytes.Value == null)
                throw new ArgumentNullException(nameof(usageBytes), "Property is not nullable for class GetStorage200ResponseTopMailboxesInner.");

            return new GetStorage200ResponseTopMailboxesInner(email, usageBytes);
        }

        /// <summary>
        /// Serializes a <see cref="GetStorage200ResponseTopMailboxesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getStorage200ResponseTopMailboxesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetStorage200ResponseTopMailboxesInner getStorage200ResponseTopMailboxesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getStorage200ResponseTopMailboxesInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetStorage200ResponseTopMailboxesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getStorage200ResponseTopMailboxesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetStorage200ResponseTopMailboxesInner getStorage200ResponseTopMailboxesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getStorage200ResponseTopMailboxesInner.EmailOption.IsSet && getStorage200ResponseTopMailboxesInner.Email == null)
                throw new ArgumentNullException(nameof(getStorage200ResponseTopMailboxesInner.Email), "Property is required for class GetStorage200ResponseTopMailboxesInner.");

            if (getStorage200ResponseTopMailboxesInner.EmailOption.IsSet)
                writer.WriteString("email", getStorage200ResponseTopMailboxesInner.Email);

            if (getStorage200ResponseTopMailboxesInner.UsageBytesOption.IsSet)
                writer.WriteNumber("usage_bytes", getStorage200ResponseTopMailboxesInner.UsageBytesOption.Value!.Value);
        }
    }
}
