// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// Migration
    /// </summary>
    public partial class Migration : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Migration" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="tenantId">tenantId</param>
        /// <param name="credentialId">credentialId</param>
        /// <param name="name">name</param>
        /// <param name="status">status</param>
        /// <param name="sourceProvider">sourceProvider</param>
        /// <param name="mailboxCount">mailboxCount</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="sourceSummary">sourceSummary</param>
        /// <param name="settings">settings</param>
        /// <param name="errorMessage">errorMessage</param>
        /// <param name="startedAt">startedAt</param>
        /// <param name="completedAt">completedAt</param>
        [JsonConstructor]
        public Migration(Guid id, Guid tenantId, Guid credentialId, string name, StatusEnum status, string sourceProvider, int mailboxCount, DateTime createdAt, DateTime updatedAt, Option<string?> sourceSummary = default, Option<MigrationSettings?> settings = default, Option<string?> errorMessage = default, Option<DateTime?> startedAt = default, Option<DateTime?> completedAt = default)
        {
            Id = id;
            TenantId = tenantId;
            CredentialId = credentialId;
            Name = name;
            Status = status;
            SourceProvider = sourceProvider;
            MailboxCount = mailboxCount;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            SourceSummaryOption = sourceSummary;
            SettingsOption = settings;
            ErrorMessageOption = errorMessage;
            StartedAtOption = startedAt;
            CompletedAtOption = completedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Draft for value: draft
            /// </summary>
            Draft = 1,

            /// <summary>
            /// Enum Discovering for value: discovering
            /// </summary>
            Discovering = 2,

            /// <summary>
            /// Enum Discovered for value: discovered
            /// </summary>
            Discovered = 3,

            /// <summary>
            /// Enum Mapped for value: mapped
            /// </summary>
            Mapped = 4,

            /// <summary>
            /// Enum PilotRunning for value: pilot_running
            /// </summary>
            PilotRunning = 5,

            /// <summary>
            /// Enum PilotComplete for value: pilot_complete
            /// </summary>
            PilotComplete = 6,

            /// <summary>
            /// Enum Running for value: running
            /// </summary>
            Running = 7,

            /// <summary>
            /// Enum Staged for value: staged
            /// </summary>
            Staged = 8,

            /// <summary>
            /// Enum CutoverPending for value: cutover_pending
            /// </summary>
            CutoverPending = 9,

            /// <summary>
            /// Enum FinalSyncing for value: final_syncing
            /// </summary>
            FinalSyncing = 10,

            /// <summary>
            /// Enum Validating for value: validating
            /// </summary>
            Validating = 11,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            Completed = 12,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 13,

            /// <summary>
            /// Enum Cancelled for value: cancelled
            /// </summary>
            Cancelled = 14
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("draft"))
                return StatusEnum.Draft;

            if (value.Equals("discovering"))
                return StatusEnum.Discovering;

            if (value.Equals("discovered"))
                return StatusEnum.Discovered;

            if (value.Equals("mapped"))
                return StatusEnum.Mapped;

            if (value.Equals("pilot_running"))
                return StatusEnum.PilotRunning;

            if (value.Equals("pilot_complete"))
                return StatusEnum.PilotComplete;

            if (value.Equals("running"))
                return StatusEnum.Running;

            if (value.Equals("staged"))
                return StatusEnum.Staged;

            if (value.Equals("cutover_pending"))
                return StatusEnum.CutoverPending;

            if (value.Equals("final_syncing"))
                return StatusEnum.FinalSyncing;

            if (value.Equals("validating"))
                return StatusEnum.Validating;

            if (value.Equals("completed"))
                return StatusEnum.Completed;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            if (value.Equals("cancelled"))
                return StatusEnum.Cancelled;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("draft"))
                return StatusEnum.Draft;

            if (value.Equals("discovering"))
                return StatusEnum.Discovering;

            if (value.Equals("discovered"))
                return StatusEnum.Discovered;

            if (value.Equals("mapped"))
                return StatusEnum.Mapped;

            if (value.Equals("pilot_running"))
                return StatusEnum.PilotRunning;

            if (value.Equals("pilot_complete"))
                return StatusEnum.PilotComplete;

            if (value.Equals("running"))
                return StatusEnum.Running;

            if (value.Equals("staged"))
                return StatusEnum.Staged;

            if (value.Equals("cutover_pending"))
                return StatusEnum.CutoverPending;

            if (value.Equals("final_syncing"))
                return StatusEnum.FinalSyncing;

            if (value.Equals("validating"))
                return StatusEnum.Validating;

            if (value.Equals("completed"))
                return StatusEnum.Completed;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            if (value.Equals("cancelled"))
                return StatusEnum.Cancelled;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Draft)
                return "draft";

            if (value == StatusEnum.Discovering)
                return "discovering";

            if (value == StatusEnum.Discovered)
                return "discovered";

            if (value == StatusEnum.Mapped)
                return "mapped";

            if (value == StatusEnum.PilotRunning)
                return "pilot_running";

            if (value == StatusEnum.PilotComplete)
                return "pilot_complete";

            if (value == StatusEnum.Running)
                return "running";

            if (value == StatusEnum.Staged)
                return "staged";

            if (value == StatusEnum.CutoverPending)
                return "cutover_pending";

            if (value == StatusEnum.FinalSyncing)
                return "final_syncing";

            if (value == StatusEnum.Validating)
                return "validating";

            if (value == StatusEnum.Completed)
                return "completed";

            if (value == StatusEnum.Failed)
                return "failed";

            if (value == StatusEnum.Cancelled)
                return "cancelled";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenant_id")]
        public Guid TenantId { get; set; }

        /// <summary>
        /// Gets or Sets CredentialId
        /// </summary>
        [JsonPropertyName("credential_id")]
        public Guid CredentialId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets SourceProvider
        /// </summary>
        [JsonPropertyName("source_provider")]
        public string SourceProvider { get; set; }

        /// <summary>
        /// Gets or Sets MailboxCount
        /// </summary>
        [JsonPropertyName("mailbox_count")]
        public int MailboxCount { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Used to track the state of SourceSummary
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceSummaryOption { get; private set; }

        /// <summary>
        /// Gets or Sets SourceSummary
        /// </summary>
        [JsonPropertyName("source_summary")]
        public string? SourceSummary { get { return this.SourceSummaryOption.Value; } set { this.SourceSummaryOption = new(value); } }

        /// <summary>
        /// Used to track the state of Settings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MigrationSettings?> SettingsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Settings
        /// </summary>
        [JsonPropertyName("settings")]
        public MigrationSettings? Settings { get { return this.SettingsOption.Value; } set { this.SettingsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ErrorMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets ErrorMessage
        /// </summary>
        [JsonPropertyName("error_message")]
        public string? ErrorMessage { get { return this.ErrorMessageOption.Value; } set { this.ErrorMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of StartedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> StartedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets StartedAt
        /// </summary>
        [JsonPropertyName("started_at")]
        public DateTime? StartedAt { get { return this.StartedAtOption.Value; } set { this.StartedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompletedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CompletedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompletedAt
        /// </summary>
        [JsonPropertyName("completed_at")]
        public DateTime? CompletedAt { get { return this.CompletedAtOption.Value; } set { this.CompletedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Migration {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  CredentialId: ").Append(CredentialId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  SourceProvider: ").Append(SourceProvider).Append("\n");
            sb.Append("  MailboxCount: ").Append(MailboxCount).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  SourceSummary: ").Append(SourceSummary).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("  StartedAt: ").Append(StartedAt).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Migration" />
    /// </summary>
    public class MigrationJsonConverter : JsonConverter<Migration>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize StartedAt
        /// </summary>
        public static string StartedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CompletedAt
        /// </summary>
        public static string CompletedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Migration" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Migration Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> tenantId = default;
            Option<Guid?> credentialId = default;
            Option<string?> name = default;
            Option<Migration.StatusEnum?> status = default;
            Option<string?> sourceProvider = default;
            Option<int?> mailboxCount = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> updatedAt = default;
            Option<string?> sourceSummary = default;
            Option<MigrationSettings?> settings = default;
            Option<string?> errorMessage = default;
            Option<DateTime?> startedAt = default;
            Option<DateTime?> completedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "tenant_id":
                            tenantId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "credential_id":
                            credentialId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<Migration.StatusEnum?>(Migration.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "source_provider":
                            sourceProvider = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mailbox_count":
                            mailboxCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updated_at":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "source_summary":
                            sourceSummary = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "settings":
                            settings = new Option<MigrationSettings?>(JsonSerializer.Deserialize<MigrationSettings>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "error_message":
                            errorMessage = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "started_at":
                            startedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "completed_at":
                            completedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Migration.", nameof(id));

            if (!tenantId.IsSet)
                throw new ArgumentException("Property is required for class Migration.", nameof(tenantId));

            if (!credentialId.IsSet)
                throw new ArgumentException("Property is required for class Migration.", nameof(credentialId));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class Migration.", nameof(name));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class Migration.", nameof(status));

            if (!sourceProvider.IsSet)
                throw new ArgumentException("Property is required for class Migration.", nameof(sourceProvider));

            if (!mailboxCount.IsSet)
                throw new ArgumentException("Property is required for class Migration.", nameof(mailboxCount));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class Migration.", nameof(createdAt));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class Migration.", nameof(updatedAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Migration.");

            if (tenantId.IsSet && tenantId.Value == null)
                throw new ArgumentNullException(nameof(tenantId), "Property is not nullable for class Migration.");

            if (credentialId.IsSet && credentialId.Value == null)
                throw new ArgumentNullException(nameof(credentialId), "Property is not nullable for class Migration.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class Migration.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class Migration.");

            if (sourceProvider.IsSet && sourceProvider.Value == null)
                throw new ArgumentNullException(nameof(sourceProvider), "Property is not nullable for class Migration.");

            if (mailboxCount.IsSet && mailboxCount.Value == null)
                throw new ArgumentNullException(nameof(mailboxCount), "Property is not nullable for class Migration.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Migration.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class Migration.");

            if (sourceSummary.IsSet && sourceSummary.Value == null)
                throw new ArgumentNullException(nameof(sourceSummary), "Property is not nullable for class Migration.");

            if (settings.IsSet && settings.Value == null)
                throw new ArgumentNullException(nameof(settings), "Property is not nullable for class Migration.");

            if (errorMessage.IsSet && errorMessage.Value == null)
                throw new ArgumentNullException(nameof(errorMessage), "Property is not nullable for class Migration.");

            if (startedAt.IsSet && startedAt.Value == null)
                throw new ArgumentNullException(nameof(startedAt), "Property is not nullable for class Migration.");

            if (completedAt.IsSet && completedAt.Value == null)
                throw new ArgumentNullException(nameof(completedAt), "Property is not nullable for class Migration.");

            return new Migration(id.Value!.Value!, tenantId.Value!.Value!, credentialId.Value!.Value!, name.Value!, status.Value!.Value!, sourceProvider.Value!, mailboxCount.Value!.Value!, createdAt.Value!.Value!, updatedAt.Value!.Value!, sourceSummary, settings, errorMessage, startedAt, completedAt);
        }

        /// <summary>
        /// Serializes a <see cref="Migration" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="migration"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Migration migration, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, migration, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Migration" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="migration"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Migration migration, JsonSerializerOptions jsonSerializerOptions)
        {
            if (migration.Name == null)
                throw new ArgumentNullException(nameof(migration.Name), "Property is required for class Migration.");

            if (migration.SourceProvider == null)
                throw new ArgumentNullException(nameof(migration.SourceProvider), "Property is required for class Migration.");

            if (migration.SourceSummaryOption.IsSet && migration.SourceSummary == null)
                throw new ArgumentNullException(nameof(migration.SourceSummary), "Property is required for class Migration.");

            if (migration.SettingsOption.IsSet && migration.Settings == null)
                throw new ArgumentNullException(nameof(migration.Settings), "Property is required for class Migration.");

            if (migration.ErrorMessageOption.IsSet && migration.ErrorMessage == null)
                throw new ArgumentNullException(nameof(migration.ErrorMessage), "Property is required for class Migration.");

            writer.WriteString("id", migration.Id);

            writer.WriteString("tenant_id", migration.TenantId);

            writer.WriteString("credential_id", migration.CredentialId);

            writer.WriteString("name", migration.Name);

            var statusRawValue = Migration.StatusEnumToJsonValue(migration.Status);
            writer.WriteString("status", statusRawValue);
            writer.WriteString("source_provider", migration.SourceProvider);

            writer.WriteNumber("mailbox_count", migration.MailboxCount);

            writer.WriteString("created_at", migration.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("updated_at", migration.UpdatedAt.ToString(UpdatedAtFormat));

            if (migration.SourceSummaryOption.IsSet)
                writer.WriteString("source_summary", migration.SourceSummary);

            if (migration.SettingsOption.IsSet)
            {
                writer.WritePropertyName("settings");
                JsonSerializer.Serialize(writer, migration.Settings, jsonSerializerOptions);
            }
            if (migration.ErrorMessageOption.IsSet)
                writer.WriteString("error_message", migration.ErrorMessage);

            if (migration.StartedAtOption.IsSet)
                writer.WriteString("started_at", migration.StartedAtOption.Value!.Value.ToString(StartedAtFormat));

            if (migration.CompletedAtOption.IsSet)
                writer.WriteString("completed_at", migration.CompletedAtOption.Value!.Value.ToString(CompletedAtFormat));
        }
    }
}
