// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// MigrationCredential
    /// </summary>
    public partial class MigrationCredential : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MigrationCredential" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="tenantId">tenantId</param>
        /// <param name="provider">provider</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="encryptionKeyId">encryptionKeyId</param>
        /// <param name="label">label</param>
        [JsonConstructor]
        public MigrationCredential(Guid id, Guid tenantId, ProviderEnum provider, DateTime createdAt, DateTime updatedAt, Option<string?> encryptionKeyId = default, Option<string?> label = default)
        {
            Id = id;
            TenantId = tenantId;
            Provider = provider;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            EncryptionKeyIdOption = encryptionKeyId;
            LabelOption = label;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Provider
        /// </summary>
        public enum ProviderEnum
        {
            /// <summary>
            /// Enum Imap for value: imap
            /// </summary>
            Imap = 1,

            /// <summary>
            /// Enum Google for value: google
            /// </summary>
            Google = 2,

            /// <summary>
            /// Enum Microsoft for value: microsoft
            /// </summary>
            Microsoft = 3,

            /// <summary>
            /// Enum Generic for value: generic
            /// </summary>
            Generic = 4
        }

        /// <summary>
        /// Returns a <see cref="ProviderEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ProviderEnum ProviderEnumFromString(string value)
        {
            if (value.Equals("imap"))
                return ProviderEnum.Imap;

            if (value.Equals("google"))
                return ProviderEnum.Google;

            if (value.Equals("microsoft"))
                return ProviderEnum.Microsoft;

            if (value.Equals("generic"))
                return ProviderEnum.Generic;

            throw new NotImplementedException($"Could not convert value to type ProviderEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ProviderEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ProviderEnum? ProviderEnumFromStringOrDefault(string value)
        {
            if (value.Equals("imap"))
                return ProviderEnum.Imap;

            if (value.Equals("google"))
                return ProviderEnum.Google;

            if (value.Equals("microsoft"))
                return ProviderEnum.Microsoft;

            if (value.Equals("generic"))
                return ProviderEnum.Generic;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ProviderEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ProviderEnumToJsonValue(ProviderEnum value)
        {
            if (value == ProviderEnum.Imap)
                return "imap";

            if (value == ProviderEnum.Google)
                return "google";

            if (value == ProviderEnum.Microsoft)
                return "microsoft";

            if (value == ProviderEnum.Generic)
                return "generic";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Provider
        /// </summary>
        [JsonPropertyName("provider")]
        public ProviderEnum Provider { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenant_id")]
        public Guid TenantId { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Used to track the state of EncryptionKeyId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EncryptionKeyIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets EncryptionKeyId
        /// </summary>
        [JsonPropertyName("encryption_key_id")]
        public string? EncryptionKeyId { get { return this.EncryptionKeyIdOption.Value; } set { this.EncryptionKeyIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Label
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LabelOption { get; private set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [JsonPropertyName("label")]
        public string? Label { get { return this.LabelOption.Value; } set { this.LabelOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MigrationCredential {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  EncryptionKeyId: ").Append(EncryptionKeyId).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MigrationCredential" />
    /// </summary>
    public class MigrationCredentialJsonConverter : JsonConverter<MigrationCredential>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="MigrationCredential" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MigrationCredential Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> tenantId = default;
            Option<MigrationCredential.ProviderEnum?> provider = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> updatedAt = default;
            Option<string?> encryptionKeyId = default;
            Option<string?> label = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "tenant_id":
                            tenantId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "provider":
                            string? providerRawValue = utf8JsonReader.GetString();
                            if (providerRawValue != null)
                                provider = new Option<MigrationCredential.ProviderEnum?>(MigrationCredential.ProviderEnumFromStringOrDefault(providerRawValue));
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updated_at":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "encryption_key_id":
                            encryptionKeyId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "label":
                            label = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class MigrationCredential.", nameof(id));

            if (!tenantId.IsSet)
                throw new ArgumentException("Property is required for class MigrationCredential.", nameof(tenantId));

            if (!provider.IsSet)
                throw new ArgumentException("Property is required for class MigrationCredential.", nameof(provider));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class MigrationCredential.", nameof(createdAt));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class MigrationCredential.", nameof(updatedAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class MigrationCredential.");

            if (tenantId.IsSet && tenantId.Value == null)
                throw new ArgumentNullException(nameof(tenantId), "Property is not nullable for class MigrationCredential.");

            if (provider.IsSet && provider.Value == null)
                throw new ArgumentNullException(nameof(provider), "Property is not nullable for class MigrationCredential.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class MigrationCredential.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class MigrationCredential.");

            if (encryptionKeyId.IsSet && encryptionKeyId.Value == null)
                throw new ArgumentNullException(nameof(encryptionKeyId), "Property is not nullable for class MigrationCredential.");

            if (label.IsSet && label.Value == null)
                throw new ArgumentNullException(nameof(label), "Property is not nullable for class MigrationCredential.");

            return new MigrationCredential(id.Value!.Value!, tenantId.Value!.Value!, provider.Value!.Value!, createdAt.Value!.Value!, updatedAt.Value!.Value!, encryptionKeyId, label);
        }

        /// <summary>
        /// Serializes a <see cref="MigrationCredential" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="migrationCredential"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MigrationCredential migrationCredential, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, migrationCredential, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MigrationCredential" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="migrationCredential"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MigrationCredential migrationCredential, JsonSerializerOptions jsonSerializerOptions)
        {
            if (migrationCredential.EncryptionKeyIdOption.IsSet && migrationCredential.EncryptionKeyId == null)
                throw new ArgumentNullException(nameof(migrationCredential.EncryptionKeyId), "Property is required for class MigrationCredential.");

            if (migrationCredential.LabelOption.IsSet && migrationCredential.Label == null)
                throw new ArgumentNullException(nameof(migrationCredential.Label), "Property is required for class MigrationCredential.");

            writer.WriteString("id", migrationCredential.Id);

            writer.WriteString("tenant_id", migrationCredential.TenantId);

            var providerRawValue = MigrationCredential.ProviderEnumToJsonValue(migrationCredential.Provider);
            writer.WriteString("provider", providerRawValue);
            writer.WriteString("created_at", migrationCredential.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("updated_at", migrationCredential.UpdatedAt.ToString(UpdatedAtFormat));

            if (migrationCredential.EncryptionKeyIdOption.IsSet)
                writer.WriteString("encryption_key_id", migrationCredential.EncryptionKeyId);

            if (migrationCredential.LabelOption.IsSet)
                writer.WriteString("label", migrationCredential.Label);
        }
    }
}
