// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// SendMessage
    /// </summary>
    public partial class SendMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendMessage" /> class.
        /// </summary>
        /// <param name="from">from</param>
        /// <param name="to">to</param>
        /// <param name="cc">cc</param>
        /// <param name="bcc">bcc</param>
        /// <param name="subject">subject</param>
        /// <param name="text">text</param>
        /// <param name="html">html</param>
        /// <param name="headers">headers</param>
        /// <param name="unsubscribe">unsubscribe</param>
        /// <param name="templateId">templateId</param>
        /// <param name="variables">variables</param>
        /// <param name="sendAt">sendAt</param>
        /// <param name="attachments">attachments</param>
        [JsonConstructor]
        public SendMessage(string from, List<string> to, Option<List<string>?> cc = default, Option<List<string>?> bcc = default, Option<string?> subject = default, Option<string?> text = default, Option<string?> html = default, Option<Dictionary<string, string>?> headers = default, Option<bool?> unsubscribe = default, Option<Guid?> templateId = default, Option<Dictionary<string, string>?> variables = default, Option<DateTime?> sendAt = default, Option<List<V1SendPostRequestAttachmentsInner>?> attachments = default)
        {
            From = from;
            To = to;
            CcOption = cc;
            BccOption = bcc;
            SubjectOption = subject;
            TextOption = text;
            HtmlOption = html;
            HeadersOption = headers;
            UnsubscribeOption = unsubscribe;
            TemplateIdOption = templateId;
            VariablesOption = variables;
            SendAtOption = sendAt;
            AttachmentsOption = attachments;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets From
        /// </summary>
        [JsonPropertyName("from")]
        public string From { get; set; }

        /// <summary>
        /// Gets or Sets To
        /// </summary>
        [JsonPropertyName("to")]
        public List<string> To { get; set; }

        /// <summary>
        /// Used to track the state of Cc
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> CcOption { get; private set; }

        /// <summary>
        /// Gets or Sets Cc
        /// </summary>
        [JsonPropertyName("cc")]
        public List<string>? Cc { get { return this.CcOption.Value; } set { this.CcOption = new(value); } }

        /// <summary>
        /// Used to track the state of Bcc
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> BccOption { get; private set; }

        /// <summary>
        /// Gets or Sets Bcc
        /// </summary>
        [JsonPropertyName("bcc")]
        public List<string>? Bcc { get { return this.BccOption.Value; } set { this.BccOption = new(value); } }

        /// <summary>
        /// Used to track the state of Subject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SubjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        [JsonPropertyName("subject")]
        public string? Subject { get { return this.SubjectOption.Value; } set { this.SubjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of Text
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TextOption { get; private set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [JsonPropertyName("text")]
        public string? Text { get { return this.TextOption.Value; } set { this.TextOption = new(value); } }

        /// <summary>
        /// Used to track the state of Html
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HtmlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Html
        /// </summary>
        [JsonPropertyName("html")]
        public string? Html { get { return this.HtmlOption.Value; } set { this.HtmlOption = new(value); } }

        /// <summary>
        /// Used to track the state of Headers
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> HeadersOption { get; private set; }

        /// <summary>
        /// Gets or Sets Headers
        /// </summary>
        [JsonPropertyName("headers")]
        public Dictionary<string, string>? Headers { get { return this.HeadersOption.Value; } set { this.HeadersOption = new(value); } }

        /// <summary>
        /// Used to track the state of Unsubscribe
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> UnsubscribeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Unsubscribe
        /// </summary>
        [JsonPropertyName("unsubscribe")]
        public bool? Unsubscribe { get { return this.UnsubscribeOption.Value; } set { this.UnsubscribeOption = new(value); } }

        /// <summary>
        /// Used to track the state of TemplateId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> TemplateIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TemplateId
        /// </summary>
        [JsonPropertyName("template_id")]
        public Guid? TemplateId { get { return this.TemplateIdOption.Value; } set { this.TemplateIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Variables
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> VariablesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Variables
        /// </summary>
        [JsonPropertyName("variables")]
        public Dictionary<string, string>? Variables { get { return this.VariablesOption.Value; } set { this.VariablesOption = new(value); } }

        /// <summary>
        /// Used to track the state of SendAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> SendAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets SendAt
        /// </summary>
        [JsonPropertyName("send_at")]
        public DateTime? SendAt { get { return this.SendAtOption.Value; } set { this.SendAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of Attachments
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<V1SendPostRequestAttachmentsInner>?> AttachmentsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Attachments
        /// </summary>
        [JsonPropertyName("attachments")]
        public List<V1SendPostRequestAttachmentsInner>? Attachments { get { return this.AttachmentsOption.Value; } set { this.AttachmentsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendMessage {\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Cc: ").Append(Cc).Append("\n");
            sb.Append("  Bcc: ").Append(Bcc).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Html: ").Append(Html).Append("\n");
            sb.Append("  Headers: ").Append(Headers).Append("\n");
            sb.Append("  Unsubscribe: ").Append(Unsubscribe).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  Variables: ").Append(Variables).Append("\n");
            sb.Append("  SendAt: ").Append(SendAt).Append("\n");
            sb.Append("  Attachments: ").Append(Attachments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SendMessage" />
    /// </summary>
    public class SendMessageJsonConverter : JsonConverter<SendMessage>
    {
        /// <summary>
        /// The format to use to serialize SendAt
        /// </summary>
        public static string SendAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="SendMessage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SendMessage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> from = default;
            Option<List<string>?> to = default;
            Option<List<string>?> cc = default;
            Option<List<string>?> bcc = default;
            Option<string?> subject = default;
            Option<string?> text = default;
            Option<string?> html = default;
            Option<Dictionary<string, string>?> headers = default;
            Option<bool?> unsubscribe = default;
            Option<Guid?> templateId = default;
            Option<Dictionary<string, string>?> variables = default;
            Option<DateTime?> sendAt = default;
            Option<List<V1SendPostRequestAttachmentsInner>?> attachments = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "from":
                            from = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "to":
                            to = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "cc":
                            cc = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "bcc":
                            bcc = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "text":
                            text = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "html":
                            html = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "headers":
                            headers = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "unsubscribe":
                            unsubscribe = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "template_id":
                            templateId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "variables":
                            variables = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "send_at":
                            sendAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "attachments":
                            attachments = new Option<List<V1SendPostRequestAttachmentsInner>?>(JsonSerializer.Deserialize<List<V1SendPostRequestAttachmentsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!from.IsSet)
                throw new ArgumentException("Property is required for class SendMessage.", nameof(from));

            if (!to.IsSet)
                throw new ArgumentException("Property is required for class SendMessage.", nameof(to));

            if (from.IsSet && from.Value == null)
                throw new ArgumentNullException(nameof(from), "Property is not nullable for class SendMessage.");

            if (to.IsSet && to.Value == null)
                throw new ArgumentNullException(nameof(to), "Property is not nullable for class SendMessage.");

            if (cc.IsSet && cc.Value == null)
                throw new ArgumentNullException(nameof(cc), "Property is not nullable for class SendMessage.");

            if (bcc.IsSet && bcc.Value == null)
                throw new ArgumentNullException(nameof(bcc), "Property is not nullable for class SendMessage.");

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class SendMessage.");

            if (text.IsSet && text.Value == null)
                throw new ArgumentNullException(nameof(text), "Property is not nullable for class SendMessage.");

            if (html.IsSet && html.Value == null)
                throw new ArgumentNullException(nameof(html), "Property is not nullable for class SendMessage.");

            if (headers.IsSet && headers.Value == null)
                throw new ArgumentNullException(nameof(headers), "Property is not nullable for class SendMessage.");

            if (unsubscribe.IsSet && unsubscribe.Value == null)
                throw new ArgumentNullException(nameof(unsubscribe), "Property is not nullable for class SendMessage.");

            if (templateId.IsSet && templateId.Value == null)
                throw new ArgumentNullException(nameof(templateId), "Property is not nullable for class SendMessage.");

            if (variables.IsSet && variables.Value == null)
                throw new ArgumentNullException(nameof(variables), "Property is not nullable for class SendMessage.");

            if (sendAt.IsSet && sendAt.Value == null)
                throw new ArgumentNullException(nameof(sendAt), "Property is not nullable for class SendMessage.");

            if (attachments.IsSet && attachments.Value == null)
                throw new ArgumentNullException(nameof(attachments), "Property is not nullable for class SendMessage.");

            return new SendMessage(from.Value!, to.Value!, cc, bcc, subject, text, html, headers, unsubscribe, templateId, variables, sendAt, attachments);
        }

        /// <summary>
        /// Serializes a <see cref="SendMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SendMessage sendMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sendMessage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SendMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SendMessage sendMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sendMessage.From == null)
                throw new ArgumentNullException(nameof(sendMessage.From), "Property is required for class SendMessage.");

            if (sendMessage.To == null)
                throw new ArgumentNullException(nameof(sendMessage.To), "Property is required for class SendMessage.");

            if (sendMessage.CcOption.IsSet && sendMessage.Cc == null)
                throw new ArgumentNullException(nameof(sendMessage.Cc), "Property is required for class SendMessage.");

            if (sendMessage.BccOption.IsSet && sendMessage.Bcc == null)
                throw new ArgumentNullException(nameof(sendMessage.Bcc), "Property is required for class SendMessage.");

            if (sendMessage.SubjectOption.IsSet && sendMessage.Subject == null)
                throw new ArgumentNullException(nameof(sendMessage.Subject), "Property is required for class SendMessage.");

            if (sendMessage.TextOption.IsSet && sendMessage.Text == null)
                throw new ArgumentNullException(nameof(sendMessage.Text), "Property is required for class SendMessage.");

            if (sendMessage.HtmlOption.IsSet && sendMessage.Html == null)
                throw new ArgumentNullException(nameof(sendMessage.Html), "Property is required for class SendMessage.");

            if (sendMessage.HeadersOption.IsSet && sendMessage.Headers == null)
                throw new ArgumentNullException(nameof(sendMessage.Headers), "Property is required for class SendMessage.");

            if (sendMessage.VariablesOption.IsSet && sendMessage.Variables == null)
                throw new ArgumentNullException(nameof(sendMessage.Variables), "Property is required for class SendMessage.");

            if (sendMessage.AttachmentsOption.IsSet && sendMessage.Attachments == null)
                throw new ArgumentNullException(nameof(sendMessage.Attachments), "Property is required for class SendMessage.");

            writer.WriteString("from", sendMessage.From);

            writer.WritePropertyName("to");
            JsonSerializer.Serialize(writer, sendMessage.To, jsonSerializerOptions);
            if (sendMessage.CcOption.IsSet)
            {
                writer.WritePropertyName("cc");
                JsonSerializer.Serialize(writer, sendMessage.Cc, jsonSerializerOptions);
            }
            if (sendMessage.BccOption.IsSet)
            {
                writer.WritePropertyName("bcc");
                JsonSerializer.Serialize(writer, sendMessage.Bcc, jsonSerializerOptions);
            }
            if (sendMessage.SubjectOption.IsSet)
                writer.WriteString("subject", sendMessage.Subject);

            if (sendMessage.TextOption.IsSet)
                writer.WriteString("text", sendMessage.Text);

            if (sendMessage.HtmlOption.IsSet)
                writer.WriteString("html", sendMessage.Html);

            if (sendMessage.HeadersOption.IsSet)
            {
                writer.WritePropertyName("headers");
                JsonSerializer.Serialize(writer, sendMessage.Headers, jsonSerializerOptions);
            }
            if (sendMessage.UnsubscribeOption.IsSet)
                writer.WriteBoolean("unsubscribe", sendMessage.UnsubscribeOption.Value!.Value);

            if (sendMessage.TemplateIdOption.IsSet)
                writer.WriteString("template_id", sendMessage.TemplateIdOption.Value!.Value);

            if (sendMessage.VariablesOption.IsSet)
            {
                writer.WritePropertyName("variables");
                JsonSerializer.Serialize(writer, sendMessage.Variables, jsonSerializerOptions);
            }
            if (sendMessage.SendAtOption.IsSet)
                writer.WriteString("send_at", sendMessage.SendAtOption.Value!.Value.ToString(SendAtFormat));

            if (sendMessage.AttachmentsOption.IsSet)
            {
                writer.WritePropertyName("attachments");
                JsonSerializer.Serialize(writer, sendMessage.Attachments, jsonSerializerOptions);
            }
        }
    }
}
