// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// SignupRequest
    /// </summary>
    public partial class SignupRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignupRequest" /> class.
        /// </summary>
        /// <param name="slug">slug</param>
        /// <param name="adminEmail">adminEmail</param>
        /// <param name="password">password</param>
        /// <param name="displayName">displayName</param>
        /// <param name="mode">mode (default to ModeEnum.Business)</param>
        [JsonConstructor]
        public SignupRequest(string slug, string adminEmail, string password, Option<string?> displayName = default, Option<ModeEnum?> mode = default)
        {
            Slug = slug;
            AdminEmail = adminEmail;
            Password = password;
            DisplayNameOption = displayName;
            ModeOption = mode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Mode
        /// </summary>
        public enum ModeEnum
        {
            /// <summary>
            /// Enum Api for value: api
            /// </summary>
            Api = 1,

            /// <summary>
            /// Enum Business for value: business
            /// </summary>
            Business = 2,

            /// <summary>
            /// Enum Both for value: both
            /// </summary>
            Both = 3
        }

        /// <summary>
        /// Returns a <see cref="ModeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ModeEnum ModeEnumFromString(string value)
        {
            if (value.Equals("api"))
                return ModeEnum.Api;

            if (value.Equals("business"))
                return ModeEnum.Business;

            if (value.Equals("both"))
                return ModeEnum.Both;

            throw new NotImplementedException($"Could not convert value to type ModeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ModeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ModeEnum? ModeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("api"))
                return ModeEnum.Api;

            if (value.Equals("business"))
                return ModeEnum.Business;

            if (value.Equals("both"))
                return ModeEnum.Both;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ModeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ModeEnumToJsonValue(ModeEnum? value)
        {
            if (value == ModeEnum.Api)
                return "api";

            if (value == ModeEnum.Business)
                return "business";

            if (value == ModeEnum.Both)
                return "both";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Mode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ModeEnum?> ModeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Mode
        /// </summary>
        [JsonPropertyName("mode")]
        public ModeEnum? Mode { get { return this.ModeOption.Value; } set { this.ModeOption = new(value); } }

        /// <summary>
        /// Gets or Sets Slug
        /// </summary>
        [JsonPropertyName("slug")]
        public string Slug { get; set; }

        /// <summary>
        /// Gets or Sets AdminEmail
        /// </summary>
        [JsonPropertyName("admin_email")]
        public string AdminEmail { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [JsonPropertyName("password")]
        public string Password { get; set; }

        /// <summary>
        /// Used to track the state of DisplayName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DisplayNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [JsonPropertyName("display_name")]
        public string? DisplayName { get { return this.DisplayNameOption.Value; } set { this.DisplayNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignupRequest {\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  AdminEmail: ").Append(AdminEmail).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Password (string) minLength
            if (this.Password != null && this.Password.Length < 12)
            {
                yield return new ValidationResult("Invalid value for Password, length must be greater than 12.", new [] { "Password" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SignupRequest" />
    /// </summary>
    public class SignupRequestJsonConverter : JsonConverter<SignupRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="SignupRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SignupRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> slug = default;
            Option<string?> adminEmail = default;
            Option<string?> password = default;
            Option<string?> displayName = default;
            Option<SignupRequest.ModeEnum?> mode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "slug":
                            slug = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "admin_email":
                            adminEmail = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "password":
                            password = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "display_name":
                            displayName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mode":
                            string? modeRawValue = utf8JsonReader.GetString();
                            if (modeRawValue != null)
                                mode = new Option<SignupRequest.ModeEnum?>(SignupRequest.ModeEnumFromStringOrDefault(modeRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!slug.IsSet)
                throw new ArgumentException("Property is required for class SignupRequest.", nameof(slug));

            if (!adminEmail.IsSet)
                throw new ArgumentException("Property is required for class SignupRequest.", nameof(adminEmail));

            if (!password.IsSet)
                throw new ArgumentException("Property is required for class SignupRequest.", nameof(password));

            if (slug.IsSet && slug.Value == null)
                throw new ArgumentNullException(nameof(slug), "Property is not nullable for class SignupRequest.");

            if (adminEmail.IsSet && adminEmail.Value == null)
                throw new ArgumentNullException(nameof(adminEmail), "Property is not nullable for class SignupRequest.");

            if (password.IsSet && password.Value == null)
                throw new ArgumentNullException(nameof(password), "Property is not nullable for class SignupRequest.");

            if (displayName.IsSet && displayName.Value == null)
                throw new ArgumentNullException(nameof(displayName), "Property is not nullable for class SignupRequest.");

            if (mode.IsSet && mode.Value == null)
                throw new ArgumentNullException(nameof(mode), "Property is not nullable for class SignupRequest.");

            return new SignupRequest(slug.Value!, adminEmail.Value!, password.Value!, displayName, mode);
        }

        /// <summary>
        /// Serializes a <see cref="SignupRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="signupRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SignupRequest signupRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, signupRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SignupRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="signupRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SignupRequest signupRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (signupRequest.Slug == null)
                throw new ArgumentNullException(nameof(signupRequest.Slug), "Property is required for class SignupRequest.");

            if (signupRequest.AdminEmail == null)
                throw new ArgumentNullException(nameof(signupRequest.AdminEmail), "Property is required for class SignupRequest.");

            if (signupRequest.Password == null)
                throw new ArgumentNullException(nameof(signupRequest.Password), "Property is required for class SignupRequest.");

            if (signupRequest.DisplayNameOption.IsSet && signupRequest.DisplayName == null)
                throw new ArgumentNullException(nameof(signupRequest.DisplayName), "Property is required for class SignupRequest.");

            writer.WriteString("slug", signupRequest.Slug);

            writer.WriteString("admin_email", signupRequest.AdminEmail);

            writer.WriteString("password", signupRequest.Password);

            if (signupRequest.DisplayNameOption.IsSet)
                writer.WriteString("display_name", signupRequest.DisplayName);

            var modeRawValue = SignupRequest.ModeEnumToJsonValue(signupRequest.ModeOption.Value!.Value);
            writer.WriteString("mode", modeRawValue);
        }
    }
}
