// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// StartMigration202Response
    /// </summary>
    public partial class StartMigration202Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StartMigration202Response" /> class.
        /// </summary>
        /// <param name="status">status</param>
        /// <param name="mailboxesQueued">mailboxesQueued</param>
        [JsonConstructor]
        public StartMigration202Response(string status, int mailboxesQueued)
        {
            Status = status;
            MailboxesQueued = mailboxesQueued;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets MailboxesQueued
        /// </summary>
        [JsonPropertyName("mailboxes_queued")]
        public int MailboxesQueued { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StartMigration202Response {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  MailboxesQueued: ").Append(MailboxesQueued).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StartMigration202Response" />
    /// </summary>
    public class StartMigration202ResponseJsonConverter : JsonConverter<StartMigration202Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="StartMigration202Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override StartMigration202Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> status = default;
            Option<int?> mailboxesQueued = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mailboxes_queued":
                            mailboxesQueued = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class StartMigration202Response.", nameof(status));

            if (!mailboxesQueued.IsSet)
                throw new ArgumentException("Property is required for class StartMigration202Response.", nameof(mailboxesQueued));

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class StartMigration202Response.");

            if (mailboxesQueued.IsSet && mailboxesQueued.Value == null)
                throw new ArgumentNullException(nameof(mailboxesQueued), "Property is not nullable for class StartMigration202Response.");

            return new StartMigration202Response(status.Value!, mailboxesQueued.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="StartMigration202Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="startMigration202Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, StartMigration202Response startMigration202Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, startMigration202Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="StartMigration202Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="startMigration202Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, StartMigration202Response startMigration202Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (startMigration202Response.Status == null)
                throw new ArgumentNullException(nameof(startMigration202Response.Status), "Property is required for class StartMigration202Response.");

            writer.WriteString("status", startMigration202Response.Status);

            writer.WriteNumber("mailboxes_queued", startMigration202Response.MailboxesQueued);
        }
    }
}
