// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// Suppression
    /// </summary>
    public partial class Suppression : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Suppression" /> class.
        /// </summary>
        /// <param name="email">email</param>
        /// <param name="reason">reason</param>
        /// <param name="source">source</param>
        /// <param name="createdAt">createdAt</param>
        [JsonConstructor]
        public Suppression(Option<string?> email = default, Option<ReasonEnum?> reason = default, Option<string?> source = default, Option<DateTime?> createdAt = default)
        {
            EmailOption = email;
            ReasonOption = reason;
            SourceOption = source;
            CreatedAtOption = createdAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Reason
        /// </summary>
        public enum ReasonEnum
        {
            /// <summary>
            /// Enum Unsubscribe for value: unsubscribe
            /// </summary>
            Unsubscribe = 1,

            /// <summary>
            /// Enum Complaint for value: complaint
            /// </summary>
            Complaint = 2,

            /// <summary>
            /// Enum Bounce for value: bounce
            /// </summary>
            Bounce = 3,

            /// <summary>
            /// Enum Manual for value: manual
            /// </summary>
            Manual = 4
        }

        /// <summary>
        /// Returns a <see cref="ReasonEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ReasonEnum ReasonEnumFromString(string value)
        {
            if (value.Equals("unsubscribe"))
                return ReasonEnum.Unsubscribe;

            if (value.Equals("complaint"))
                return ReasonEnum.Complaint;

            if (value.Equals("bounce"))
                return ReasonEnum.Bounce;

            if (value.Equals("manual"))
                return ReasonEnum.Manual;

            throw new NotImplementedException($"Could not convert value to type ReasonEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ReasonEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ReasonEnum? ReasonEnumFromStringOrDefault(string value)
        {
            if (value.Equals("unsubscribe"))
                return ReasonEnum.Unsubscribe;

            if (value.Equals("complaint"))
                return ReasonEnum.Complaint;

            if (value.Equals("bounce"))
                return ReasonEnum.Bounce;

            if (value.Equals("manual"))
                return ReasonEnum.Manual;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ReasonEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ReasonEnumToJsonValue(ReasonEnum? value)
        {
            if (value == ReasonEnum.Unsubscribe)
                return "unsubscribe";

            if (value == ReasonEnum.Complaint)
                return "complaint";

            if (value == ReasonEnum.Bounce)
                return "bounce";

            if (value == ReasonEnum.Manual)
                return "manual";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Reason
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ReasonEnum?> ReasonOption { get; private set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [JsonPropertyName("reason")]
        public ReasonEnum? Reason { get { return this.ReasonOption.Value; } set { this.ReasonOption = new(value); } }

        /// <summary>
        /// Used to track the state of Email
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string? Email { get { return this.EmailOption.Value; } set { this.EmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of Source
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [JsonPropertyName("source")]
        public string? Source { get { return this.SourceOption.Value; } set { this.SourceOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime? CreatedAt { get { return this.CreatedAtOption.Value; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Suppression {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Suppression" />
    /// </summary>
    public class SuppressionJsonConverter : JsonConverter<Suppression>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Suppression" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Suppression Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> email = default;
            Option<Suppression.ReasonEnum?> reason = default;
            Option<string?> source = default;
            Option<DateTime?> createdAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "reason":
                            string? reasonRawValue = utf8JsonReader.GetString();
                            if (reasonRawValue != null)
                                reason = new Option<Suppression.ReasonEnum?>(Suppression.ReasonEnumFromStringOrDefault(reasonRawValue));
                            break;
                        case "source":
                            source = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class Suppression.");

            if (reason.IsSet && reason.Value == null)
                throw new ArgumentNullException(nameof(reason), "Property is not nullable for class Suppression.");

            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source), "Property is not nullable for class Suppression.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Suppression.");

            return new Suppression(email, reason, source, createdAt);
        }

        /// <summary>
        /// Serializes a <see cref="Suppression" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="suppression"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Suppression suppression, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, suppression, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Suppression" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="suppression"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Suppression suppression, JsonSerializerOptions jsonSerializerOptions)
        {
            if (suppression.EmailOption.IsSet && suppression.Email == null)
                throw new ArgumentNullException(nameof(suppression.Email), "Property is required for class Suppression.");

            if (suppression.SourceOption.IsSet && suppression.Source == null)
                throw new ArgumentNullException(nameof(suppression.Source), "Property is required for class Suppression.");

            if (suppression.EmailOption.IsSet)
                writer.WriteString("email", suppression.Email);

            var reasonRawValue = Suppression.ReasonEnumToJsonValue(suppression.ReasonOption.Value!.Value);
            writer.WriteString("reason", reasonRawValue);
            if (suppression.SourceOption.IsSet)
                writer.WriteString("source", suppression.Source);

            if (suppression.CreatedAtOption.IsSet)
                writer.WriteString("created_at", suppression.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));
        }
    }
}
