// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// UpdateGALSettingsRequest
    /// </summary>
    public partial class UpdateGALSettingsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateGALSettingsRequest" /> class.
        /// </summary>
        /// <param name="galEnabled">galEnabled</param>
        /// <param name="hideFromDirectory">hideFromDirectory</param>
        /// <param name="departmentGrouping">departmentGrouping</param>
        /// <param name="searchVisibility">searchVisibility</param>
        /// <param name="includeExternalContacts">includeExternalContacts</param>
        [JsonConstructor]
        public UpdateGALSettingsRequest(Option<bool?> galEnabled = default, Option<bool?> hideFromDirectory = default, Option<bool?> departmentGrouping = default, Option<SearchVisibilityEnum?> searchVisibility = default, Option<bool?> includeExternalContacts = default)
        {
            GalEnabledOption = galEnabled;
            HideFromDirectoryOption = hideFromDirectory;
            DepartmentGroupingOption = departmentGrouping;
            SearchVisibilityOption = searchVisibility;
            IncludeExternalContactsOption = includeExternalContacts;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines SearchVisibility
        /// </summary>
        public enum SearchVisibilityEnum
        {
            /// <summary>
            /// Enum AllUsers for value: all_users
            /// </summary>
            AllUsers = 1,

            /// <summary>
            /// Enum SameDepartment for value: same_department
            /// </summary>
            SameDepartment = 2,

            /// <summary>
            /// Enum AdminsOnly for value: admins_only
            /// </summary>
            AdminsOnly = 3
        }

        /// <summary>
        /// Returns a <see cref="SearchVisibilityEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static SearchVisibilityEnum SearchVisibilityEnumFromString(string value)
        {
            if (value.Equals("all_users"))
                return SearchVisibilityEnum.AllUsers;

            if (value.Equals("same_department"))
                return SearchVisibilityEnum.SameDepartment;

            if (value.Equals("admins_only"))
                return SearchVisibilityEnum.AdminsOnly;

            throw new NotImplementedException($"Could not convert value to type SearchVisibilityEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="SearchVisibilityEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchVisibilityEnum? SearchVisibilityEnumFromStringOrDefault(string value)
        {
            if (value.Equals("all_users"))
                return SearchVisibilityEnum.AllUsers;

            if (value.Equals("same_department"))
                return SearchVisibilityEnum.SameDepartment;

            if (value.Equals("admins_only"))
                return SearchVisibilityEnum.AdminsOnly;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SearchVisibilityEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string SearchVisibilityEnumToJsonValue(SearchVisibilityEnum? value)
        {
            if (value == SearchVisibilityEnum.AllUsers)
                return "all_users";

            if (value == SearchVisibilityEnum.SameDepartment)
                return "same_department";

            if (value == SearchVisibilityEnum.AdminsOnly)
                return "admins_only";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of SearchVisibility
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SearchVisibilityEnum?> SearchVisibilityOption { get; private set; }

        /// <summary>
        /// Gets or Sets SearchVisibility
        /// </summary>
        [JsonPropertyName("search_visibility")]
        public SearchVisibilityEnum? SearchVisibility { get { return this.SearchVisibilityOption.Value; } set { this.SearchVisibilityOption = new(value); } }

        /// <summary>
        /// Used to track the state of GalEnabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> GalEnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets GalEnabled
        /// </summary>
        [JsonPropertyName("gal_enabled")]
        public bool? GalEnabled { get { return this.GalEnabledOption.Value; } set { this.GalEnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of HideFromDirectory
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> HideFromDirectoryOption { get; private set; }

        /// <summary>
        /// Gets or Sets HideFromDirectory
        /// </summary>
        [JsonPropertyName("hide_from_directory")]
        public bool? HideFromDirectory { get { return this.HideFromDirectoryOption.Value; } set { this.HideFromDirectoryOption = new(value); } }

        /// <summary>
        /// Used to track the state of DepartmentGrouping
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DepartmentGroupingOption { get; private set; }

        /// <summary>
        /// Gets or Sets DepartmentGrouping
        /// </summary>
        [JsonPropertyName("department_grouping")]
        public bool? DepartmentGrouping { get { return this.DepartmentGroupingOption.Value; } set { this.DepartmentGroupingOption = new(value); } }

        /// <summary>
        /// Used to track the state of IncludeExternalContacts
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IncludeExternalContactsOption { get; private set; }

        /// <summary>
        /// Gets or Sets IncludeExternalContacts
        /// </summary>
        [JsonPropertyName("include_external_contacts")]
        public bool? IncludeExternalContacts { get { return this.IncludeExternalContactsOption.Value; } set { this.IncludeExternalContactsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateGALSettingsRequest {\n");
            sb.Append("  GalEnabled: ").Append(GalEnabled).Append("\n");
            sb.Append("  HideFromDirectory: ").Append(HideFromDirectory).Append("\n");
            sb.Append("  DepartmentGrouping: ").Append(DepartmentGrouping).Append("\n");
            sb.Append("  SearchVisibility: ").Append(SearchVisibility).Append("\n");
            sb.Append("  IncludeExternalContacts: ").Append(IncludeExternalContacts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateGALSettingsRequest" />
    /// </summary>
    public class UpdateGALSettingsRequestJsonConverter : JsonConverter<UpdateGALSettingsRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateGALSettingsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateGALSettingsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> galEnabled = default;
            Option<bool?> hideFromDirectory = default;
            Option<bool?> departmentGrouping = default;
            Option<UpdateGALSettingsRequest.SearchVisibilityEnum?> searchVisibility = default;
            Option<bool?> includeExternalContacts = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "gal_enabled":
                            galEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "hide_from_directory":
                            hideFromDirectory = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "department_grouping":
                            departmentGrouping = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "search_visibility":
                            string? searchVisibilityRawValue = utf8JsonReader.GetString();
                            if (searchVisibilityRawValue != null)
                                searchVisibility = new Option<UpdateGALSettingsRequest.SearchVisibilityEnum?>(UpdateGALSettingsRequest.SearchVisibilityEnumFromStringOrDefault(searchVisibilityRawValue));
                            break;
                        case "include_external_contacts":
                            includeExternalContacts = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (galEnabled.IsSet && galEnabled.Value == null)
                throw new ArgumentNullException(nameof(galEnabled), "Property is not nullable for class UpdateGALSettingsRequest.");

            if (hideFromDirectory.IsSet && hideFromDirectory.Value == null)
                throw new ArgumentNullException(nameof(hideFromDirectory), "Property is not nullable for class UpdateGALSettingsRequest.");

            if (departmentGrouping.IsSet && departmentGrouping.Value == null)
                throw new ArgumentNullException(nameof(departmentGrouping), "Property is not nullable for class UpdateGALSettingsRequest.");

            if (searchVisibility.IsSet && searchVisibility.Value == null)
                throw new ArgumentNullException(nameof(searchVisibility), "Property is not nullable for class UpdateGALSettingsRequest.");

            if (includeExternalContacts.IsSet && includeExternalContacts.Value == null)
                throw new ArgumentNullException(nameof(includeExternalContacts), "Property is not nullable for class UpdateGALSettingsRequest.");

            return new UpdateGALSettingsRequest(galEnabled, hideFromDirectory, departmentGrouping, searchVisibility, includeExternalContacts);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateGALSettingsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateGALSettingsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateGALSettingsRequest updateGALSettingsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateGALSettingsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateGALSettingsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateGALSettingsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateGALSettingsRequest updateGALSettingsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateGALSettingsRequest.GalEnabledOption.IsSet)
                writer.WriteBoolean("gal_enabled", updateGALSettingsRequest.GalEnabledOption.Value!.Value);

            if (updateGALSettingsRequest.HideFromDirectoryOption.IsSet)
                writer.WriteBoolean("hide_from_directory", updateGALSettingsRequest.HideFromDirectoryOption.Value!.Value);

            if (updateGALSettingsRequest.DepartmentGroupingOption.IsSet)
                writer.WriteBoolean("department_grouping", updateGALSettingsRequest.DepartmentGroupingOption.Value!.Value);

            var searchVisibilityRawValue = UpdateGALSettingsRequest.SearchVisibilityEnumToJsonValue(updateGALSettingsRequest.SearchVisibilityOption.Value!.Value);
            writer.WriteString("search_visibility", searchVisibilityRawValue);
            if (updateGALSettingsRequest.IncludeExternalContactsOption.IsSet)
                writer.WriteBoolean("include_external_contacts", updateGALSettingsRequest.IncludeExternalContactsOption.Value!.Value);
        }
    }
}
