// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// V1AdminLoginPost200Response
    /// </summary>
    public partial class V1AdminLoginPost200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1AdminLoginPost200Response" /> class.
        /// </summary>
        /// <param name="token">token</param>
        /// <param name="expiresAt">expiresAt</param>
        /// <param name="admin">admin</param>
        /// <param name="tenant">tenant</param>
        [JsonConstructor]
        public V1AdminLoginPost200Response(string token, DateTime expiresAt, Admin admin, Tenant tenant)
        {
            Token = token;
            ExpiresAt = expiresAt;
            Admin = admin;
            Tenant = tenant;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Token
        /// </summary>
        /* <example>adm_sess_...</example> */
        [JsonPropertyName("token")]
        public string Token { get; set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [JsonPropertyName("expires_at")]
        public DateTime ExpiresAt { get; set; }

        /// <summary>
        /// Gets or Sets Admin
        /// </summary>
        [JsonPropertyName("admin")]
        public Admin Admin { get; set; }

        /// <summary>
        /// Gets or Sets Tenant
        /// </summary>
        [JsonPropertyName("tenant")]
        public Tenant Tenant { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1AdminLoginPost200Response {\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  Admin: ").Append(Admin).Append("\n");
            sb.Append("  Tenant: ").Append(Tenant).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V1AdminLoginPost200Response" />
    /// </summary>
    public class V1AdminLoginPost200ResponseJsonConverter : JsonConverter<V1AdminLoginPost200Response>
    {
        /// <summary>
        /// The format to use to serialize ExpiresAt
        /// </summary>
        public static string ExpiresAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="V1AdminLoginPost200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V1AdminLoginPost200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> token = default;
            Option<DateTime?> expiresAt = default;
            Option<Admin?> admin = default;
            Option<Tenant?> tenant = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "token":
                            token = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "expires_at":
                            expiresAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "admin":
                            admin = new Option<Admin?>(JsonSerializer.Deserialize<Admin>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "tenant":
                            tenant = new Option<Tenant?>(JsonSerializer.Deserialize<Tenant>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!token.IsSet)
                throw new ArgumentException("Property is required for class V1AdminLoginPost200Response.", nameof(token));

            if (!expiresAt.IsSet)
                throw new ArgumentException("Property is required for class V1AdminLoginPost200Response.", nameof(expiresAt));

            if (!admin.IsSet)
                throw new ArgumentException("Property is required for class V1AdminLoginPost200Response.", nameof(admin));

            if (!tenant.IsSet)
                throw new ArgumentException("Property is required for class V1AdminLoginPost200Response.", nameof(tenant));

            if (token.IsSet && token.Value == null)
                throw new ArgumentNullException(nameof(token), "Property is not nullable for class V1AdminLoginPost200Response.");

            if (expiresAt.IsSet && expiresAt.Value == null)
                throw new ArgumentNullException(nameof(expiresAt), "Property is not nullable for class V1AdminLoginPost200Response.");

            if (admin.IsSet && admin.Value == null)
                throw new ArgumentNullException(nameof(admin), "Property is not nullable for class V1AdminLoginPost200Response.");

            if (tenant.IsSet && tenant.Value == null)
                throw new ArgumentNullException(nameof(tenant), "Property is not nullable for class V1AdminLoginPost200Response.");

            return new V1AdminLoginPost200Response(token.Value!, expiresAt.Value!.Value!, admin.Value!, tenant.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="V1AdminLoginPost200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v1AdminLoginPost200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V1AdminLoginPost200Response v1AdminLoginPost200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v1AdminLoginPost200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V1AdminLoginPost200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v1AdminLoginPost200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V1AdminLoginPost200Response v1AdminLoginPost200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v1AdminLoginPost200Response.Token == null)
                throw new ArgumentNullException(nameof(v1AdminLoginPost200Response.Token), "Property is required for class V1AdminLoginPost200Response.");

            if (v1AdminLoginPost200Response.Admin == null)
                throw new ArgumentNullException(nameof(v1AdminLoginPost200Response.Admin), "Property is required for class V1AdminLoginPost200Response.");

            if (v1AdminLoginPost200Response.Tenant == null)
                throw new ArgumentNullException(nameof(v1AdminLoginPost200Response.Tenant), "Property is required for class V1AdminLoginPost200Response.");

            writer.WriteString("token", v1AdminLoginPost200Response.Token);

            writer.WriteString("expires_at", v1AdminLoginPost200Response.ExpiresAt.ToString(ExpiresAtFormat));

            writer.WritePropertyName("admin");
            JsonSerializer.Serialize(writer, v1AdminLoginPost200Response.Admin, jsonSerializerOptions);
            writer.WritePropertyName("tenant");
            JsonSerializer.Serialize(writer, v1AdminLoginPost200Response.Tenant, jsonSerializerOptions);
        }
    }
}
