// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// V1MailboxesEmailPatchRequest
    /// </summary>
    public partial class V1MailboxesEmailPatchRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1MailboxesEmailPatchRequest" /> class.
        /// </summary>
        /// <param name="password">password</param>
        /// <param name="quotaBytes">quotaBytes</param>
        /// <param name="disabled">disabled</param>
        [JsonConstructor]
        public V1MailboxesEmailPatchRequest(Option<string?> password = default, Option<long?> quotaBytes = default, Option<bool?> disabled = default)
        {
            PasswordOption = password;
            QuotaBytesOption = quotaBytes;
            DisabledOption = disabled;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Password
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PasswordOption { get; private set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [JsonPropertyName("password")]
        public string? Password { get { return this.PasswordOption.Value; } set { this.PasswordOption = new(value); } }

        /// <summary>
        /// Used to track the state of QuotaBytes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> QuotaBytesOption { get; private set; }

        /// <summary>
        /// Gets or Sets QuotaBytes
        /// </summary>
        [JsonPropertyName("quota_bytes")]
        public long? QuotaBytes { get { return this.QuotaBytesOption.Value; } set { this.QuotaBytesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Disabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DisabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets Disabled
        /// </summary>
        [JsonPropertyName("disabled")]
        public bool? Disabled { get { return this.DisabledOption.Value; } set { this.DisabledOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1MailboxesEmailPatchRequest {\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  QuotaBytes: ").Append(QuotaBytes).Append("\n");
            sb.Append("  Disabled: ").Append(Disabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Password (string) minLength
            if (this.Password != null && this.Password.Length < 8)
            {
                yield return new ValidationResult("Invalid value for Password, length must be greater than 8.", new [] { "Password" });
            }

            // QuotaBytes (long) minimum
            if (this.QuotaBytesOption.IsSet && this.QuotaBytesOption.Value < (long)0)
            {
                yield return new ValidationResult("Invalid value for QuotaBytes, must be a value greater than or equal to 0.", new [] { "QuotaBytes" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V1MailboxesEmailPatchRequest" />
    /// </summary>
    public class V1MailboxesEmailPatchRequestJsonConverter : JsonConverter<V1MailboxesEmailPatchRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="V1MailboxesEmailPatchRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V1MailboxesEmailPatchRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> password = default;
            Option<long?> quotaBytes = default;
            Option<bool?> disabled = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "password":
                            password = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "quota_bytes":
                            quotaBytes = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "disabled":
                            disabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (password.IsSet && password.Value == null)
                throw new ArgumentNullException(nameof(password), "Property is not nullable for class V1MailboxesEmailPatchRequest.");

            if (quotaBytes.IsSet && quotaBytes.Value == null)
                throw new ArgumentNullException(nameof(quotaBytes), "Property is not nullable for class V1MailboxesEmailPatchRequest.");

            if (disabled.IsSet && disabled.Value == null)
                throw new ArgumentNullException(nameof(disabled), "Property is not nullable for class V1MailboxesEmailPatchRequest.");

            return new V1MailboxesEmailPatchRequest(password, quotaBytes, disabled);
        }

        /// <summary>
        /// Serializes a <see cref="V1MailboxesEmailPatchRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v1MailboxesEmailPatchRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V1MailboxesEmailPatchRequest v1MailboxesEmailPatchRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v1MailboxesEmailPatchRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V1MailboxesEmailPatchRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v1MailboxesEmailPatchRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V1MailboxesEmailPatchRequest v1MailboxesEmailPatchRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v1MailboxesEmailPatchRequest.PasswordOption.IsSet && v1MailboxesEmailPatchRequest.Password == null)
                throw new ArgumentNullException(nameof(v1MailboxesEmailPatchRequest.Password), "Property is required for class V1MailboxesEmailPatchRequest.");

            if (v1MailboxesEmailPatchRequest.PasswordOption.IsSet)
                writer.WriteString("password", v1MailboxesEmailPatchRequest.Password);

            if (v1MailboxesEmailPatchRequest.QuotaBytesOption.IsSet)
                writer.WriteNumber("quota_bytes", v1MailboxesEmailPatchRequest.QuotaBytesOption.Value!.Value);

            if (v1MailboxesEmailPatchRequest.DisabledOption.IsSet)
                writer.WriteBoolean("disabled", v1MailboxesEmailPatchRequest.DisabledOption.Value!.Value);
        }
    }
}
