// <auto-generated>
/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Lockally.SDK.Client;

namespace Lockally.SDK.Model
{
    /// <summary>
    /// Webhook
    /// </summary>
    public partial class Webhook : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Webhook" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="tenantId">tenantId</param>
        /// <param name="url">url</param>
        /// <param name="events">events</param>
        /// <param name="paused">paused</param>
        /// <param name="consecutiveFailures">consecutiveFailures</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="pausedAt">pausedAt</param>
        /// <param name="lastSuccessAt">lastSuccessAt</param>
        /// <param name="lastFailureAt">lastFailureAt</param>
        /// <param name="signingSecret">Hex-encoded HMAC-SHA256 key. Present ONLY on POST response.</param>
        [JsonConstructor]
        public Webhook(Guid id, Guid tenantId, string url, List<string> events, bool paused, int consecutiveFailures, DateTime createdAt, Option<DateTime?> pausedAt = default, Option<DateTime?> lastSuccessAt = default, Option<DateTime?> lastFailureAt = default, Option<string?> signingSecret = default)
        {
            Id = id;
            TenantId = tenantId;
            Url = url;
            Events = events;
            Paused = paused;
            ConsecutiveFailures = consecutiveFailures;
            CreatedAt = createdAt;
            PausedAtOption = pausedAt;
            LastSuccessAtOption = lastSuccessAt;
            LastFailureAtOption = lastFailureAt;
            SigningSecretOption = signingSecret;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenant_id")]
        public Guid TenantId { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Events
        /// </summary>
        [JsonPropertyName("events")]
        public List<string> Events { get; set; }

        /// <summary>
        /// Gets or Sets Paused
        /// </summary>
        [JsonPropertyName("paused")]
        public bool Paused { get; set; }

        /// <summary>
        /// Gets or Sets ConsecutiveFailures
        /// </summary>
        [JsonPropertyName("consecutive_failures")]
        public int ConsecutiveFailures { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of PausedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> PausedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets PausedAt
        /// </summary>
        [JsonPropertyName("paused_at")]
        public DateTime? PausedAt { get { return this.PausedAtOption.Value; } set { this.PausedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastSuccessAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> LastSuccessAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastSuccessAt
        /// </summary>
        [JsonPropertyName("last_success_at")]
        public DateTime? LastSuccessAt { get { return this.LastSuccessAtOption.Value; } set { this.LastSuccessAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastFailureAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> LastFailureAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastFailureAt
        /// </summary>
        [JsonPropertyName("last_failure_at")]
        public DateTime? LastFailureAt { get { return this.LastFailureAtOption.Value; } set { this.LastFailureAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of SigningSecret
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SigningSecretOption { get; private set; }

        /// <summary>
        /// Hex-encoded HMAC-SHA256 key. Present ONLY on POST response.
        /// </summary>
        /// <value>Hex-encoded HMAC-SHA256 key. Present ONLY on POST response.</value>
        [JsonPropertyName("signing_secret")]
        public string? SigningSecret { get { return this.SigningSecretOption.Value; } set { this.SigningSecretOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Webhook {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("  Paused: ").Append(Paused).Append("\n");
            sb.Append("  ConsecutiveFailures: ").Append(ConsecutiveFailures).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  PausedAt: ").Append(PausedAt).Append("\n");
            sb.Append("  LastSuccessAt: ").Append(LastSuccessAt).Append("\n");
            sb.Append("  LastFailureAt: ").Append(LastFailureAt).Append("\n");
            sb.Append("  SigningSecret: ").Append(SigningSecret).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Webhook" />
    /// </summary>
    public class WebhookJsonConverter : JsonConverter<Webhook>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize PausedAt
        /// </summary>
        public static string PausedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize LastSuccessAt
        /// </summary>
        public static string LastSuccessAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize LastFailureAt
        /// </summary>
        public static string LastFailureAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Webhook" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Webhook Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> tenantId = default;
            Option<string?> url = default;
            Option<List<string>?> events = default;
            Option<bool?> paused = default;
            Option<int?> consecutiveFailures = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> pausedAt = default;
            Option<DateTime?> lastSuccessAt = default;
            Option<DateTime?> lastFailureAt = default;
            Option<string?> signingSecret = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "tenant_id":
                            tenantId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "events":
                            events = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "paused":
                            paused = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "consecutive_failures":
                            consecutiveFailures = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "paused_at":
                            pausedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "last_success_at":
                            lastSuccessAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "last_failure_at":
                            lastFailureAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "signing_secret":
                            signingSecret = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Webhook.", nameof(id));

            if (!tenantId.IsSet)
                throw new ArgumentException("Property is required for class Webhook.", nameof(tenantId));

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class Webhook.", nameof(url));

            if (!events.IsSet)
                throw new ArgumentException("Property is required for class Webhook.", nameof(events));

            if (!paused.IsSet)
                throw new ArgumentException("Property is required for class Webhook.", nameof(paused));

            if (!consecutiveFailures.IsSet)
                throw new ArgumentException("Property is required for class Webhook.", nameof(consecutiveFailures));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class Webhook.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Webhook.");

            if (tenantId.IsSet && tenantId.Value == null)
                throw new ArgumentNullException(nameof(tenantId), "Property is not nullable for class Webhook.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class Webhook.");

            if (events.IsSet && events.Value == null)
                throw new ArgumentNullException(nameof(events), "Property is not nullable for class Webhook.");

            if (paused.IsSet && paused.Value == null)
                throw new ArgumentNullException(nameof(paused), "Property is not nullable for class Webhook.");

            if (consecutiveFailures.IsSet && consecutiveFailures.Value == null)
                throw new ArgumentNullException(nameof(consecutiveFailures), "Property is not nullable for class Webhook.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Webhook.");

            if (pausedAt.IsSet && pausedAt.Value == null)
                throw new ArgumentNullException(nameof(pausedAt), "Property is not nullable for class Webhook.");

            if (lastSuccessAt.IsSet && lastSuccessAt.Value == null)
                throw new ArgumentNullException(nameof(lastSuccessAt), "Property is not nullable for class Webhook.");

            if (lastFailureAt.IsSet && lastFailureAt.Value == null)
                throw new ArgumentNullException(nameof(lastFailureAt), "Property is not nullable for class Webhook.");

            if (signingSecret.IsSet && signingSecret.Value == null)
                throw new ArgumentNullException(nameof(signingSecret), "Property is not nullable for class Webhook.");

            return new Webhook(id.Value!.Value!, tenantId.Value!.Value!, url.Value!, events.Value!, paused.Value!.Value!, consecutiveFailures.Value!.Value!, createdAt.Value!.Value!, pausedAt, lastSuccessAt, lastFailureAt, signingSecret);
        }

        /// <summary>
        /// Serializes a <see cref="Webhook" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhook"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Webhook webhook, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, webhook, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Webhook" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhook"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Webhook webhook, JsonSerializerOptions jsonSerializerOptions)
        {
            if (webhook.Url == null)
                throw new ArgumentNullException(nameof(webhook.Url), "Property is required for class Webhook.");

            if (webhook.Events == null)
                throw new ArgumentNullException(nameof(webhook.Events), "Property is required for class Webhook.");

            if (webhook.SigningSecretOption.IsSet && webhook.SigningSecret == null)
                throw new ArgumentNullException(nameof(webhook.SigningSecret), "Property is required for class Webhook.");

            writer.WriteString("id", webhook.Id);

            writer.WriteString("tenant_id", webhook.TenantId);

            writer.WriteString("url", webhook.Url);

            writer.WritePropertyName("events");
            JsonSerializer.Serialize(writer, webhook.Events, jsonSerializerOptions);
            writer.WriteBoolean("paused", webhook.Paused);

            writer.WriteNumber("consecutive_failures", webhook.ConsecutiveFailures);

            writer.WriteString("created_at", webhook.CreatedAt.ToString(CreatedAtFormat));

            if (webhook.PausedAtOption.IsSet)
                writer.WriteString("paused_at", webhook.PausedAtOption.Value!.Value.ToString(PausedAtFormat));

            if (webhook.LastSuccessAtOption.IsSet)
                writer.WriteString("last_success_at", webhook.LastSuccessAtOption.Value!.Value.ToString(LastSuccessAtFormat));

            if (webhook.LastFailureAtOption.IsSet)
                writer.WriteString("last_failure_at", webhook.LastFailureAtOption.Value!.Value.ToString(LastFailureAtFormat));

            if (webhook.SigningSecretOption.IsSet)
                writer.WriteString("signing_secret", webhook.SigningSecret);
        }
    }
}
