/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Lockally.SDK.Api;
using Lockally.SDK.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Lockally.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing AdminApi
    /// </summary>
    public sealed class AdminApiTests : ApiTestsBase
    {
        private readonly IAdminApi _instance;

        public AdminApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IAdminApi>();
        }

        /// <summary>
        /// Test V1AdminLoginPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task V1AdminLoginPostAsyncTest()
        {
            V1AdminLoginPostRequest v1AdminLoginPostRequest = default!;
            var response = await _instance.V1AdminLoginPostAsync(v1AdminLoginPostRequest);
            var model = response.Ok();
            Assert.IsType<V1AdminLoginPost200Response>(model);
        }

        /// <summary>
        /// Test V1AdminLogoutPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task V1AdminLogoutPostAsyncTest()
        {
            await _instance.V1AdminLogoutPostAsync();
        }

        /// <summary>
        /// Test V1AdminMeGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task V1AdminMeGetAsyncTest()
        {
            var response = await _instance.V1AdminMeGetAsync();
            var model = response.Ok();
            Assert.IsType<V1AdminMeGet200Response>(model);
        }
    }
}
