/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Lockally.SDK.Api;
using Lockally.SDK.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Lockally.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing MigrationsApi
    /// </summary>
    public sealed class MigrationsApiTests : ApiTestsBase
    {
        private readonly IMigrationsApi _instance;

        public MigrationsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IMigrationsApi>();
        }

        /// <summary>
        /// Test CancelMigration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CancelMigrationAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.CancelMigrationAsync(id);
            var model = response.Ok();
            Assert.IsType<DiscoverMigration202Response>(model);
        }

        /// <summary>
        /// Test CheckMigrationDNS
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CheckMigrationDNSAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.CheckMigrationDNSAsync(id);
            var model = response.Ok();
            Assert.IsType<Object>(model);
        }

        /// <summary>
        /// Test CreateMigration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateMigrationAsyncTest()
        {
            CreateMigrationRequest createMigrationRequest = default!;
            var response = await _instance.CreateMigrationAsync(createMigrationRequest);
            var model = response.Created();
            Assert.IsType<Migration>(model);
        }

        /// <summary>
        /// Test CreateMigrationCredential
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateMigrationCredentialAsyncTest()
        {
            CreateMigrationCredentialRequest createMigrationCredentialRequest = default!;
            var response = await _instance.CreateMigrationCredentialAsync(createMigrationCredentialRequest);
            var model = response.Created();
            Assert.IsType<MigrationCredential>(model);
        }

        /// <summary>
        /// Test DeleteMigration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteMigrationAsyncTest()
        {
            Guid id = default!;
            await _instance.DeleteMigrationAsync(id);
        }

        /// <summary>
        /// Test DeleteMigrationCredential
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteMigrationCredentialAsyncTest()
        {
            Guid id = default!;
            await _instance.DeleteMigrationCredentialAsync(id);
        }

        /// <summary>
        /// Test DeltaSyncMigration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeltaSyncMigrationAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.DeltaSyncMigrationAsync(id);
            var model = response.Accepted();
            Assert.IsType<StartMigration202Response>(model);
        }

        /// <summary>
        /// Test DiscoverMigration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DiscoverMigrationAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.DiscoverMigrationAsync(id);
            var model = response.Accepted();
            Assert.IsType<DiscoverMigration202Response>(model);
        }

        /// <summary>
        /// Test FinalSyncMigration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FinalSyncMigrationAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.FinalSyncMigrationAsync(id);
            var model = response.Accepted();
            Assert.IsType<StartMigration202Response>(model);
        }

        /// <summary>
        /// Test GetMigration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetMigrationAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.GetMigrationAsync(id);
            var model = response.Ok();
            Assert.IsType<Migration>(model);
        }

        /// <summary>
        /// Test GetMigrationProgress
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetMigrationProgressAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.GetMigrationProgressAsync(id);
            var model = response.Ok();
            Assert.IsType<MigrationProgress>(model);
        }

        /// <summary>
        /// Test ListMigrationCredentials
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListMigrationCredentialsAsyncTest()
        {
            var response = await _instance.ListMigrationCredentialsAsync();
            var model = response.Ok();
            Assert.IsType<ListMigrationCredentials200Response>(model);
        }

        /// <summary>
        /// Test ListMigrationEvents
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListMigrationEventsAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.ListMigrationEventsAsync(id);
            var model = response.Ok();
            Assert.IsType<ListMigrationEvents200Response>(model);
        }

        /// <summary>
        /// Test ListMigrationMailboxes
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListMigrationMailboxesAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.ListMigrationMailboxesAsync(id);
            var model = response.Ok();
            Assert.IsType<ListMigrationMailboxes200Response>(model);
        }

        /// <summary>
        /// Test ListMigrations
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListMigrationsAsyncTest()
        {
            var response = await _instance.ListMigrationsAsync();
            var model = response.Ok();
            Assert.IsType<ListMigrations200Response>(model);
        }

        /// <summary>
        /// Test MapMigration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task MapMigrationAsyncTest()
        {
            Guid id = default!;
            MapMigrationRequest mapMigrationRequest = default!;
            var response = await _instance.MapMigrationAsync(id, mapMigrationRequest);
            var model = response.Ok();
            Assert.IsType<DiscoverMigration202Response>(model);
        }

        /// <summary>
        /// Test RetryMigration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RetryMigrationAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.RetryMigrationAsync(id);
            var model = response.Ok();
            Assert.IsType<DiscoverMigration202Response>(model);
        }

        /// <summary>
        /// Test StartMigration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task StartMigrationAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.StartMigrationAsync(id);
            var model = response.Accepted();
            Assert.IsType<StartMigration202Response>(model);
        }

        /// <summary>
        /// Test UpdateMigration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateMigrationAsyncTest()
        {
            Guid id = default!;
            UpdateMigrationRequest updateMigrationRequest = default!;
            var response = await _instance.UpdateMigrationAsync(id, updateMigrationRequest);
            var model = response.Ok();
            Assert.IsType<Migration>(model);
        }

        /// <summary>
        /// Test UpdateMigrationMailbox
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateMigrationMailboxAsyncTest()
        {
            Guid id = default!;
            Guid mbxId = default!;
            UpdateMigrationMailboxRequest updateMigrationMailboxRequest = default!;
            await _instance.UpdateMigrationMailboxAsync(id, mbxId, updateMigrationMailboxRequest);
        }

        /// <summary>
        /// Test ValidateMigration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ValidateMigrationAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.ValidateMigrationAsync(id);
            var model = response.Accepted();
            Assert.IsType<StartMigration202Response>(model);
        }
    }
}
